// Plik: lang.js
// Należy podmienić całą zawartość pliku, aby uwzględnić zmiany we wszystkich językach.

const languageStrings = {
  // English (Source)
  en: {
    pageTitle: "START ▪ maxi MENU ▪",
    guideCounter: "Items: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "No items to generate!",
    btnBack: "Back",
    btnLoad: "Load...",
    searchPlaceholder: "Search items...",
    filterAll: "FILTER",
    sortLabel: "SORT",
    sortShuffle: "Shuffle",
    sortNameAsc: "Name A - Z",
    sortNameDesc: "Name Z - A",
    sortDateAsc: "Date ↑",
    sortDateDesc: "Date ↓",
    sortSizeAsc: "Size ↑",
    sortSizeDesc: "Size ↓",
    generatorLabel: "GENERATE",
    generatorItem: "Items: {count}",
    generatorModeAll: "Generator: full pool",
    generatorModeVisible: "Generator: visible only",
    minimizeBtn: "Minimize interface",
    maximizeBtn: "Restore interface",
    viewModeFull: "View: Covers and text",
    viewModeImage: "View: Covers only",
    viewModeText: "View: Text only",
    orientationFilterAll: "Show all",
    orientationFilterVert: "Show vertical only",
    orientationFilterHoriz: "Show horizontal only",
    themeBtn: "Dark / Light mode",
    sizeLabel: "Thumbnail size",
    rowsLabel: "Number of rows",
    playBtn: "Start slideshow",
    guideInfoFormat: "Format",
    guideInfoSize: "Size",
    guideBtnOpen: "Open",
    guideBtnView: "View",
    guideBtnDownload: "Download",
    paginationFirst: "First page",
    paginationPrev: "Previous page",
    paginationNext: "Next page",
    paginationLast: "Last page",
    paginationReset: "Go to first page",
    paginationCarouselStart: "Enable auto-scroll",
    paginationCarouselStop: "Stop auto-scroll",
    mainResetBtn: "Reset view",
    btnVideo: "Video",
    videoBtnPrev: "Previous video",
    videoBtnPlay: "Play",
    videoBtnPause: "Pause",
    videoBtnOff: "Turn off video",
    videoBtnShuffle: "Shuffle video On/Off",
    videoBtnNext: "Next video",
    videoBtnReset: "Reset video settings",
    footerDate: "© 2025-10-03",
    footerDesc: "for cataloging, managing and presenting files and folders",
    footerIdleTime: "Idle",
    footerSessionTime: "Session",
    privacyTitle: "We respect your privacy",
    privacyDesc: "No cookies or tracking.",
    privacySafe: "Clean and safe code!",
    fullscreenBtn: "Fullscreen",
    fullscreenExitBtn: "Exit fullscreen",
    closeBtn: "Close",
    lightboxFxBtn: "Transition effects On/Off",
    lightboxVideoOptions: "Expand video options",
    lightboxLabelsBtn: "Show/hide labels",
    slideshowFirst: "First",
    slideshowPrev: "Previous",
    slideshowStop: "Stop",
    slideshowPlayPause: "Play/Pause",
    slideshowShuffle: "Shuffle slides On/Off",
    slideshowNext: "Next",
    slideshowLast: "Last",
    guideTagsLabel: "Tags",
    moonPhaseNames: [
      "New Moon",
      "Waxing Crescent",
      "First Quarter",
      "Waxing Gibbous",
      "Full Moon",
      "Waning Gibbous",
      "Last Quarter",
      "Waning Crescent",
    ],
  },
  // Polish
  pl: {
    pageTitle: "START ▪ maxi MENU ▪",
    guideCounter: "Pozycji: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Brak pozycji do wygenerowania!",
    btnBack: "Wstecz",
    btnLoad: "Załaduj...",
    searchPlaceholder: "Szukaj pozycji...",
    filterAll: "FILTR",
    sortLabel: "SORTUJ",
    sortShuffle: "Wymieszaj",
    sortNameAsc: "Nazwa A - Z",
    sortNameDesc: "Nazwa Z - A",
    sortDateAsc: "Data ↑",
    sortDateDesc: "Data ↓",
    sortSizeAsc: "Rozmiar ↑",
    sortSizeDesc: "Rozmiar ↓",
    generatorLabel: "LOSUJ",
    generatorItem: "Pozycji: {count}",
    generatorModeAll: "Generator: cała pula",
    generatorModeVisible: "Generator: tylko widoczne",
    minimizeBtn: "Minimalizuj interfejs",
    maximizeBtn: "Przywróć interfejs",
    viewModeFull: "Widok: Okładki i tekst",
    viewModeImage: "Widok: Tylko okładki",
    viewModeText: "Widok: Tylko tekst",
    orientationFilterAll: "Pokaż wszystkie",
    orientationFilterVert: "Pokaż tylko pionowe",
    orientationFilterHoriz: "Pokaż tylko poziome",
    themeBtn: "Tryb Ciemny / Jasny",
    sizeLabel: "Wielkość miniaturek",
    rowsLabel: "Liczba wierszy",
    playBtn: "Rozpocznij pokaz",
    guideInfoFormat: "Format",
    guideInfoSize: "Rozmiar",
    guideBtnOpen: "Otwórz",
    guideBtnView: "Zobacz",
    guideBtnDownload: "Pobierz",
    paginationFirst: "Pierwsza strona",
    paginationPrev: "Poprzednia strona",
    paginationNext: "Następna strona",
    paginationLast: "Ostatnia strona",
    paginationReset: "Przejść do pierwszej strony",
    paginationCarouselStart: "Włącz automatyczne przewijanie",
    paginationCarouselStop: "Zatrzymaj automatyczne przewijanie",
    mainResetBtn: "Resetuj widok",
    btnVideo: "Wideo",
    videoBtnPrev: "Poprzednie wideo",
    videoBtnPlay: "Odtwarzaj",
    videoBtnPause: "Pauza",
    videoBtnOff: "Wyłącz wideo",
    videoBtnShuffle: "Losowe wideo Wł/Wył",
    videoBtnNext: "Następne wideo",
    videoBtnReset: "Resetuj ustawienia wideo",
    footerDate: "© 2025-10-03",
    footerDesc: "do katalogowania, zarządzania i prezentacji plików i folderów",
    footerIdleTime: "Bezczynność",
    footerSessionTime: "Sesja",
    privacyTitle: "Szanujemy Twoją prywatność",
    privacyDesc: "Żadnych ciasteczek ani śledzenia.",
    privacySafe: "Czysty i bezpieczny kod!",
    fullscreenBtn: "Pełny ekran",
    fullscreenExitBtn: "Wyjdź z pełnego ekranu",
    closeBtn: "Zamknij",
    lightboxFxBtn: "Animacje przejść Wł/Wył",
    lightboxVideoOptions: "Rozwiń opcje wideo",
    lightboxLabelsBtn: "Pokaż/ukryj etykiety",
    slideshowFirst: "Pierwszy",
    slideshowPrev: "Poprzedni",
    slideshowStop: "Zatrzymaj",
    slideshowPlayPause: "Play/Pauza",
    slideshowShuffle: "Losowe slajdy Wł/Wył",
    slideshowNext: "Następny",
    slideshowLast: "Ostatni",
    guideTagsLabel: "Tagi",
    moonPhaseNames: [
      "Nów",
      "Sierp przybywający",
      "Pierwsza kwadra",
      "Garb przybywający",
      "Pełnia",
      "Garb ubywający",
      "Ostatnia kwadra",
      "Sierp ubywający",
    ],
  },
  // German
  de: {
    pageTitle: "START ▪ maxi MENÜ ▪",
    guideCounter: "Elemente: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Keine Elemente zum Generieren!",
    btnBack: "Zurück",
    btnLoad: "Laden...",
    searchPlaceholder: "Elemente suchen...",
    filterAll: "FILTER",
    sortLabel: "SORTIEREN",
    sortShuffle: "Mischen",
    sortNameAsc: "Name A - Z",
    sortNameDesc: "Name Z - A",
    sortDateAsc: "Datum ↑",
    sortDateDesc: "Datum ↓",
    sortSizeAsc: "Größe ↑",
    sortSizeDesc: "Größe ↓",
    generatorLabel: "GENERIEREN",
    generatorItem: "Elemente: {count}",
    generatorModeAll: "Generator: alle Elemente",
    generatorModeVisible: "Generator: nur sichtbare",
    minimizeBtn: "Oberfläche minimieren",
    maximizeBtn: "Oberfläche wiederherstellen",
    viewModeFull: "Ansicht: Cover und Text",
    viewModeImage: "Ansicht: Nur Cover",
    viewModeText: "Ansicht: Nur Text",
    orientationFilterAll: "Alle anzeigen",
    orientationFilterVert: "Nur vertikale anzeigen",
    orientationFilterHoriz: "Nur horizontale anzeigen",
    themeBtn: "Dunkel- / Hell-Modus",
    sizeLabel: "Thumbnail-Größe",
    rowsLabel: "Anzahl der Zeilen",
    playBtn: "Diashow starten",
    guideInfoFormat: "Format",
    guideInfoSize: "Größe",
    guideBtnOpen: "Öffnen",
    guideBtnView: "Ansehen",
    guideBtnDownload: "Herunterladen",
    paginationFirst: "Erste Seite",
    paginationPrev: "Vorherige Seite",
    paginationNext: "Nächste Seite",
    paginationLast: "Letzte Seite",
    paginationReset: "Zur ersten Seite",
    paginationCarouselStart: "Auto-Scroll aktivieren",
    paginationCarouselStop: "Auto-Scroll anhalten",
    mainResetBtn: "Ansicht zurücksetzen",
    btnVideo: "Video",
    videoBtnPrev: "Voriges Video",
    videoBtnPlay: "Abspielen",
    videoBtnPause: "Pause",
    videoBtnOff: "Video ausschalten",
    videoBtnShuffle: "Zufallswiedergabe Ein/Aus",
    videoBtnNext: "Nächstes Video",
    videoBtnReset: "Videoeinstellungen zurücksetzen",
    footerDate: "© 2025-10-03",
    footerDesc:
      "zum Katalogisieren, Verwalten und Präsentieren von Dateien und Ordnern",
    footerIdleTime: "Inaktiv",
    footerSessionTime: "Sitzung",
    privacyTitle: "Wir respektieren Ihre Privatsphäre",
    privacyDesc: "Keine Cookies oder Tracking.",
    privacySafe: "Sauberer und sicherer Code!",
    fullscreenBtn: "Vollbild",
    fullscreenExitBtn: "Vollbild beenden",
    closeBtn: "Schließen",
    lightboxFxBtn: "Übergangseffekte Ein/Aus",
    lightboxVideoOptions: "Videooptionen erweitern",
    lightboxLabelsBtn: "Beschriftungen ein-/ausblenden",
    slideshowFirst: "Erstes",
    slideshowPrev: "Voriges",
    slideshowStop: "Stopp",
    slideshowPlayPause: "Play/Pause",
    slideshowShuffle: "Zufällige Folien Ein/Aus",
    slideshowNext: "Nächstes",
    slideshowLast: "Letztes",
    guideTagsLabel: "Schlagwörter",
    moonPhaseNames: [
      "Neumond",
      "Zunehmender Sichelmond",
      "Erstes Viertel",
      "Zunehmender Halbmond",
      "Vollmond",
      "Abnehmender Halbmond",
      "Letztes Viertel",
      "Abnehmender Sichelmond",
    ],
  },
  // Spanish
  es: {
    pageTitle: "INICIO ▪ maxi MENÚ ▪",
    guideCounter: "Elementos: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "¡No hay elementos para generar!",
    btnBack: "Volver",
    btnLoad: "Cargar...",
    searchPlaceholder: "Buscar elementos...",
    filterAll: "FILTRAR",
    sortLabel: "ORDENAR",
    sortShuffle: "Aleatorio",
    sortNameAsc: "Nombre A - Z",
    sortNameDesc: "Nombre Z - A",
    sortDateAsc: "Fecha ↑",
    sortDateDesc: "Fecha ↓",
    sortSizeAsc: "Tamaño ↑",
    sortSizeDesc: "Tamaño ↓",
    generatorLabel: "GENERAR",
    generatorItem: "Elementos: {count}",
    generatorModeAll: "Generador: todos",
    generatorModeVisible: "Generador: solo visibles",
    minimizeBtn: "Minimizar interfaz",
    maximizeBtn: "Restaurar interfaz",
    viewModeFull: "Vista: Portadas y texto",
    viewModeImage: "Vista: Solo portadas",
    viewModeText: "Vista: Solo texto",
    orientationFilterAll: "Mostrar todos",
    orientationFilterVert: "Mostrar solo verticales",
    orientationFilterHoriz: "Mostrar solo horizontales",
    themeBtn: "Modo Oscuro / Claro",
    sizeLabel: "Tamaño de miniatura",
    rowsLabel: "Número de filas",
    playBtn: "Iniciar presentación",
    guideInfoFormat: "Formato",
    guideInfoSize: "Tamaño",
    guideBtnOpen: "Abrir",
    guideBtnView: "Ver",
    guideBtnDownload: "Descargar",
    paginationFirst: "Primera página",
    paginationPrev: "Página anterior",
    paginationNext: "Página siguiente",
    paginationLast: "Última página",
    paginationReset: "Ir a la primera página",
    paginationCarouselStart: "Activar auto-scroll",
    paginationCarouselStop: "Detener auto-scroll",
    mainResetBtn: "Restablecer vista",
    btnVideo: "Vídeo",
    videoBtnPrev: "Vídeo anterior",
    videoBtnPlay: "Reproducir",
    videoBtnPause: "Pausa",
    videoBtnOff: "Apagar vídeo",
    videoBtnShuffle: "Vídeo aleatorio On/Off",
    videoBtnNext: "Siguiente vídeo",
    videoBtnReset: "Restablecer ajustes de vídeo",
    footerDate: "© 2025-10-03",
    footerDesc: "para catalogar, gestionar y presentar archivos y carpetas",
    footerIdleTime: "Inactividad",
    footerSessionTime: "Sesión",
    privacyTitle: "Respetamos tu privacidad",
    privacyDesc: "Sin cookies ni seguimiento.",
    privacySafe: "¡Código limpio y seguro!",
    fullscreenBtn: "Pantalla completa",
    fullscreenExitBtn: "Salir de pantalla completa",
    closeBtn: "Cerrar",
    lightboxFxBtn: "Efectos de transición On/Off",
    lightboxVideoOptions: "Expandir opciones de vídeo",
    lightboxLabelsBtn: "Mostrar/ocultar etiquetas",
    slideshowFirst: "Primero",
    slideshowPrev: "Anterior",
    slideshowStop: "Detener",
    slideshowPlayPause: "Play/Pausa",
    slideshowShuffle: "Diapositivas aleatorias On/Off",
    slideshowNext: "Siguiente",
    slideshowLast: "Último",
    guideTagsLabel: "Etiquetas",
    moonPhaseNames: [
      "Luna Nueva",
      "Luna Creciente",
      "Cuarto Creciente",
      "Gibosa Creciente",
      "Luna Llena",
      "Gibosa Menguante",
      "Cuarto Menguante",
      "Luna Menguante",
    ],
  },
  // French
  fr: {
    pageTitle: "DÉBUT ▪ maxi MENU ▪",
    guideCounter: "Éléments: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Aucun élément à générer !",
    btnBack: "Retour",
    btnLoad: "Charger...",
    searchPlaceholder: "Rechercher des éléments...",
    filterAll: "FILTRER",
    sortLabel: "TRIER",
    sortShuffle: "Aléatoire",
    sortNameAsc: "Nom A - Z",
    sortNameDesc: "Nom Z - A",
    sortDateAsc: "Date ↑",
    sortDateDesc: "Date ↓",
    sortSizeAsc: "Taille ↑",
    sortSizeDesc: "Taille ↓",
    generatorLabel: "GÉNÉRER",
    generatorItem: "Éléments : {count}",
    generatorModeAll: "Générateur : tous",
    generatorModeVisible: "Générateur : visibles uniquement",
    minimizeBtn: "Minimiser l'interface",
    maximizeBtn: "Restaurer l'interface",
    viewModeFull: "Vue : Jaquettes et texte",
    viewModeImage: "Vue : Jaquettes uniquement",
    viewModeText: "Vue : Texte uniquement",
    orientationFilterAll: "Tout afficher",
    orientationFilterVert: "Afficher verticales uniquement",
    orientationFilterHoriz: "Afficher horizontales uniquement",
    themeBtn: "Mode Sombre / Clair",
    sizeLabel: "Taille des miniatures",
    rowsLabel: "Nombre de rangées",
    playBtn: "Démarrer le diaporama",
    guideInfoFormat: "Format",
    guideInfoSize: "Taille",
    guideBtnOpen: "Ouvrir",
    guideBtnView: "Voir",
    guideBtnDownload: "Télécharger",
    paginationFirst: "Première page",
    paginationPrev: "Page précédente",
    paginationNext: "Page suivante",
    paginationLast: "Dernière page",
    paginationReset: "Aller à la première page",
    paginationCarouselStart: "Activer le défilement auto",
    paginationCarouselStop: "Arrêter le défilement auto",
    mainResetBtn: "Réinitialiser la vue",
    btnVideo: "Vidéo",
    videoBtnPrev: "Vidéo précédente",
    videoBtnPlay: "Lecture",
    videoBtnPause: "Pause",
    videoBtnOff: "Désactiver la vidéo",
    videoBtnShuffle: "Vidéo aléatoire On/Off",
    videoBtnNext: "Vidéo suivante",
    videoBtnReset: "Réinitialiser les paramètres vidéo",
    footerDate: "© 2025-10-03",
    footerDesc: "pour cataloguer, gérer et présenter des fichiers et dossiers",
    footerIdleTime: "Inactivité",
    footerSessionTime: "Session",
    privacyTitle: "Nous respectons votre vie privée",
    privacyDesc: "Pas de cookies ni de suivi.",
    privacySafe: "Code propre et sûr !",
    fullscreenBtn: "Plein écran",
    fullscreenExitBtn: "Quitter le plein écran",
    closeBtn: "Fermer",
    lightboxFxBtn: "Effets de transition On/Off",
    lightboxVideoOptions: "Développer les options vidéo",
    lightboxLabelsBtn: "Afficher/masquer les étiquettes",
    slideshowFirst: "Premier",
    slideshowPrev: "Précédent",
    slideshowStop: "Arrêter",
    slideshowPlayPause: "Play/Pause",
    slideshowShuffle: "Diapos aléatoires On/Off",
    slideshowNext: "Suivant",
    slideshowLast: "Dernier",
    guideTagsLabel: "Mots-clés",
    moonPhaseNames: [
      "Nouvelle Lune",
      "Premier Croissant",
      "Premier Quartier",
      "Gibbeuse Croissante",
      "Pleine Lune",
      "Gibbeuse Décroissante",
      "Dernier Quartier",
      "Dernier Croissant",
    ],
  },
  // Italian
  it: {
    pageTitle: "INIZIO ▪ maxi MENU ▪",
    guideCounter: "Elementi: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Nessun elemento da generare!",
    btnBack: "Indietro",
    btnLoad: "Carica...",
    searchPlaceholder: "Cerca elementi...",
    filterAll: "FILTRA",
    sortLabel: "ORDINA",
    sortShuffle: "Casuale",
    sortNameAsc: "Nome A - Z",
    sortNameDesc: "Nome Z - A",
    sortDateAsc: "Data ↑",
    sortDateDesc: "Data ↓",
    sortSizeAsc: "Dimensione ↑",
    sortSizeDesc: "Dimensione ↓",
    generatorLabel: "GENERA",
    generatorItem: "Elementi: {count}",
    generatorModeAll: "Generatore: tutti",
    generatorModeVisible: "Generatore: solo visibili",
    minimizeBtn: "Minimizza interfaccia",
    maximizeBtn: "Ripristina interfaccia",
    viewModeFull: "Vista: Copertine e testo",
    viewModeImage: "Vista: Solo copertine",
    viewModeText: "Vista: Solo testo",
    orientationFilterAll: "Mostra tutto",
    orientationFilterVert: "Mostra solo verticali",
    orientationFilterHoriz: "Mostra solo orizzontali",
    themeBtn: "Modalità Scura / Chiara",
    sizeLabel: "Dimensione miniature",
    rowsLabel: "Numero di righe",
    playBtn: "Avvia presentazione",
    guideInfoFormat: "Formato",
    guideInfoSize: "Dimensione",
    guideBtnOpen: "Apri",
    guideBtnView: "Visualizza",
    guideBtnDownload: "Scarica",
    paginationFirst: "Prima pagina",
    paginationPrev: "Pagina precedente",
    paginationNext: "Pagina successiva",
    paginationLast: "Ultima pagina",
    paginationReset: "Vai alla prima pagina",
    paginationCarouselStart: "Attiva scorrimento automatico",
    paginationCarouselStop: "Ferma scorrimento automatico",
    mainResetBtn: "Reimposta vista",
    btnVideo: "Video",
    videoBtnPrev: "Video precedente",
    videoBtnPlay: "Riproduci",
    videoBtnPause: "Pausa",
    videoBtnOff: "Disattiva video",
    videoBtnShuffle: "Video casuale On/Off",
    videoBtnNext: "Video successivo",
    videoBtnReset: "Reimposta impostazioni video",
    footerDate: "© 2025-10-03",
    footerDesc: "per catalogare, gestire e presentare file e cartelle",
    footerIdleTime: "Inattivo",
    footerSessionTime: "Sessione",
    privacyTitle: "Rispettiamo la tua privacy",
    privacyDesc: "Nessun cookie o tracciamento.",
    privacySafe: "Codice pulito e sicuro!",
    fullscreenBtn: "Schermo intero",
    fullscreenExitBtn: "Esci da schermo intero",
    closeBtn: "Chiudi",
    lightboxFxBtn: "Effetti di transizione On/Off",
    lightboxVideoOptions: "Espandi opzioni video",
    lightboxLabelsBtn: "Mostra/nascondi etichette",
    slideshowFirst: "Primo",
    slideshowPrev: "Precedente",
    slideshowStop: "Ferma",
    slideshowPlayPause: "Play/Pausa",
    slideshowShuffle: "Diapositive casuali On/Off",
    slideshowNext: "Successivo",
    slideshowLast: "Ultimo",
    guideTagsLabel: "Tag",
    moonPhaseNames: [
      "Luna Nuova",
      "Luna Crescente",
      "Primo Quarto",
      "Gibbosa Crescente",
      "Luna Piena",
      "Gibbosa Calante",
      "Ultimo Quarto",
      "Luna Calante",
    ],
  },
  // Japanese
  ja: {
    pageTitle: "スタート ▪ maxi メニュー ▪",
    guideCounter: "アイテム: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "生成するアイテムがありません！",
    btnBack: "戻る",
    btnLoad: "読み込む...",
    searchPlaceholder: "アイテムを検索...",
    filterAll: "フィルター",
    sortLabel: "ソート",
    sortShuffle: "シャッフル",
    sortNameAsc: "名前 A - Z",
    sortNameDesc: "名前 Z - A",
    sortDateAsc: "日付 ↑",
    sortDateDesc: "日付 ↓",
    sortSizeAsc: "サイズ ↑",
    sortSizeDesc: "サイズ ↓",
    generatorLabel: "生成",
    generatorItem: "アイテム: {count}",
    generatorModeAll: "ジェネレーター: 全プール",
    generatorModeVisible: "ジェネレーター: 表示のみ",
    minimizeBtn: "インターフェースを最小化",
    maximizeBtn: "インターフェースを復元",
    viewModeFull: "表示: カバーとテキスト",
    viewModeImage: "表示: カバーのみ",
    viewModeText: "表示: テキストのみ",
    orientationFilterAll: "すべて表示",
    orientationFilterVert: "縦向きのみ表示",
    orientationFilterHoriz: "横向きのみ表示",
    themeBtn: "ダーク / ライトモード",
    sizeLabel: "サムネイルサイズ",
    rowsLabel: "行数",
    playBtn: "スライドショーを開始",
    guideInfoFormat: "フォーマット",
    guideInfoSize: "サイズ",
    guideBtnOpen: "開く",
    guideBtnView: "見る",
    guideBtnDownload: "ダウンロード",
    paginationFirst: "最初のページ",
    paginationPrev: "前のページ",
    paginationNext: "次のページ",
    paginationLast: "最後のページ",
    paginationReset: "最初のページに移動",
    paginationCarouselStart: "自動スクロールを有効化",
    paginationCarouselStop: "自動スクロールを停止",
    mainResetBtn: "表示をリセット",
    btnVideo: "ビデオ",
    videoBtnPrev: "前のビデオ",
    videoBtnPlay: "再生",
    videoBtnPause: "一時停止",
    videoBtnOff: "ビデオをオフにする",
    videoBtnShuffle: "ビデオシャッフル オン/オフ",
    videoBtnNext: "次のビデオ",
    videoBtnReset: "ビデオ設定をリセット",
    footerDate: "© 2025-10-03",
    footerDesc: "ファイルとフォルダのカタログ作成、管理、表示のため",
    footerIdleTime: "アイドル",
    footerSessionTime: "セッション",
    privacyTitle: "プライバシーの尊重",
    privacyDesc: "クッキーや追跡はありません。",
    privacySafe: "クリーンで安全なコード！",
    fullscreenBtn: "フルスクリーン",
    fullscreenExitBtn: "フルスクリーンを終了",
    closeBtn: "閉じる",
    lightboxFxBtn: "トランジション効果 オン/オフ",
    lightboxVideoOptions: "ビデオオプションを展開",
    lightboxLabelsBtn: "ラベルを表示/非表示",
    slideshowFirst: "最初",
    slideshowPrev: "前へ",
    slideshowStop: "停止",
    slideshowPlayPause: "再生/一時停止",
    slideshowShuffle: "スライドシャッフル オン/オフ",
    slideshowNext: "次へ",
    slideshowLast: "最後",
    guideTagsLabel: "タグ",
    moonPhaseNames: [
      "新月",
      "三日月",
      "上弦の月",
      "十三夜月",
      "満月",
      "十六夜",
      "下弦の月",
      "有明月",
    ],
  },
  // Chinese (Simplified)
  zh: {
    pageTitle: "开始 ▪ maxi 菜单 ▪",
    guideCounter: "项目: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "没有可生成的项目！",
    btnBack: "返回",
    btnLoad: "加载...",
    searchPlaceholder: "搜索项目...",
    filterAll: "筛选",
    sortLabel: "排序",
    sortShuffle: "随机播放",
    sortNameAsc: "名称 A - Z",
    sortNameDesc: "名称 Z - A",
    sortDateAsc: "日期 ↑",
    sortDateDesc: "日期 ↓",
    sortSizeAsc: "大小 ↑",
    sortSizeDesc: "大小 ↓",
    generatorLabel: "生成",
    generatorItem: "项目: {count}",
    generatorModeAll: "生成器: 全部",
    generatorModeVisible: "生成器: 仅可见",
    minimizeBtn: "最小化界面",
    maximizeBtn: "恢复界面",
    viewModeFull: "视图: 封面和文本",
    viewModeImage: "视图: 仅封面",
    viewModeText: "视图: 仅文本",
    orientationFilterAll: "显示全部",
    orientationFilterVert: "仅显示垂直",
    orientationFilterHoriz: "仅显示水平",
    themeBtn: "深色 / 浅色模式",
    sizeLabel: "缩略图大小",
    rowsLabel: "行数",
    playBtn: "开始幻灯片",
    guideInfoFormat: "格式",
    guideInfoSize: "大小",
    guideBtnOpen: "打开",
    guideBtnView: "查看",
    guideBtnDownload: "下载",
    paginationFirst: "第一页",
    paginationPrev: "上一页",
    paginationNext: "下一页",
    paginationLast: "最后一页",
    paginationReset: "转到第一页",
    paginationCarouselStart: "启用自动滚动",
    paginationCarouselStop: "停止自动滚动",
    mainResetBtn: "重置视图",
    btnVideo: "视频",
    videoBtnPrev: "上一个视频",
    videoBtnPlay: "播放",
    videoBtnPause: "暂停",
    videoBtnOff: "关闭视频",
    videoBtnShuffle: "随机视频 开/关",
    videoBtnNext: "下一个视频",
    videoBtnReset: "重置视频设置",
    footerDate: "© 2025-10-03",
    footerDesc: "用于编目、管理和呈现文件和文件夹",
    footerIdleTime: "空闲",
    footerSessionTime: "会话",
    privacyTitle: "我们尊重您的隐私",
    privacyDesc: "无 Cookie 或跟踪。",
    privacySafe: "干净安全的代码！",
    fullscreenBtn: "全屏",
    fullscreenExitBtn: "退出全屏",
    closeBtn: "关闭",
    lightboxFxBtn: "过渡效果 开/关",
    lightboxVideoOptions: "展开视频选项",
    lightboxLabelsBtn: "显示/隐藏标签",
    slideshowFirst: "第一个",
    slideshowPrev: "上一个",
    slideshowStop: "停止",
    slideshowPlayPause: "播放/暂停",
    slideshowShuffle: "随机幻灯片 开/关",
    slideshowNext: "下一个",
    slideshowLast: "最后一个",
    guideTagsLabel: "标签",
    moonPhaseNames: [
      "新月",
      "娥眉月",
      "上弦月",
      "盈凸月",
      "满月",
      "亏凸月",
      "下弦月",
      "残月",
    ],
  },
  // Portuguese (Brazil)
  pt: {
    pageTitle: "INÍCIO ▪ maxi MENU ▪",
    guideCounter: "Itens: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Nenhum item para gerar!",
    btnBack: "Voltar",
    btnLoad: "Carregar...",
    searchPlaceholder: "Pesquisar itens...",
    filterAll: "FILTRAR",
    sortLabel: "ORDENAR",
    sortShuffle: "Aleatório",
    sortNameAsc: "Nome A - Z",
    sortNameDesc: "Nome Z - A",
    sortDateAsc: "Data ↑",
    sortDateDesc: "Data ↓",
    sortSizeAsc: "Tamanho ↑",
    sortSizeDesc: "Tamanho ↓",
    generatorLabel: "GERAR",
    generatorItem: "Itens: {count}",
    generatorModeAll: "Gerador: todos",
    generatorModeVisible: "Gerador: apenas visíveis",
    minimizeBtn: "Minimizar interface",
    maximizeBtn: "Restaurar interface",
    viewModeFull: "Visão: Capas e texto",
    viewModeImage: "Visão: Apenas capas",
    viewModeText: "Visão: Apenas texto",
    orientationFilterAll: "Mostrar todos",
    orientationFilterVert: "Mostrar apenas verticais",
    orientationFilterHoriz: "Mostrar apenas horizontais",
    themeBtn: "Modo Escuro / Claro",
    sizeLabel: "Tamanho da miniatura",
    rowsLabel: "Número de linhas",
    playBtn: "Iniciar slideshow",
    guideInfoFormat: "Formato",
    guideInfoSize: "Tamanho",
    guideBtnOpen: "Abrir",
    guideBtnView: "Ver",
    guideBtnDownload: "Baixar",
    paginationFirst: "Primeira página",
    paginationPrev: "Página anterior",
    paginationNext: "Próxima página",
    paginationLast: "Última página",
    paginationReset: "Ir para a primeira página",
    paginationCarouselStart: "Ativar rolagem automática",
    paginationCarouselStop: "Parar rolagem automática",
    mainResetBtn: "Redefinir visão",
    btnVideo: "Vídeo",
    videoBtnPrev: "Vídeo anterior",
    videoBtnPlay: "Reproduzir",
    videoBtnPause: "Pausar",
    videoBtnOff: "Desligar vídeo",
    videoBtnShuffle: "Vídeo aleatório On/Off",
    videoBtnNext: "Próximo vídeo",
    videoBtnReset: "Redefinir configurações de vídeo",
    footerDate: "© 2025-10-03",
    footerDesc: "para catalogar, gerenciar e apresentar arquivos e pastas",
    footerIdleTime: "Ocioso",
    footerSessionTime: "Sessão",
    privacyTitle: "Respeitamos sua privacidade",
    privacyDesc: "Sem cookies ou rastreamento.",
    privacySafe: "Código limpo e seguro!",
    fullscreenBtn: "Tela cheia",
    fullscreenExitBtn: "Sair da tela cheia",
    closeBtn: "Fechar",
    lightboxFxBtn: "Efeitos de transição On/Off",
    lightboxVideoOptions: "Expandir opções de vídeo",
    lightboxLabelsBtn: "Mostrar/ocultar legendas",
    slideshowFirst: "Primeiro",
    slideshowPrev: "Anterior",
    slideshowStop: "Parar",
    slideshowPlayPause: "Play/Pause",
    slideshowShuffle: "Slides aleatórios On/Off",
    slideshowNext: "Próximo",
    slideshowLast: "Último",
    guideTagsLabel: "Tags",
    moonPhaseNames: [
      "Lua Nova",
      "Lua Crescente",
      "Quarto Crescente",
      "Gibosa Crescente",
      "Lua Cheia",
      "Gibosa Minguante",
      "Quarto Minguante",
      "Lua Minguante",
    ],
  },
  // Czech
  cs: {
    pageTitle: "START ▪ maxi MENU ▪",
    guideCounter: "Položek: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Žádné položky k vygenerování!",
    btnBack: "Zpět",
    btnLoad: "Načíst...",
    searchPlaceholder: "Hledat položky...",
    filterAll: "FILTR",
    sortLabel: "ŘADIT",
    sortShuffle: "Zamíchat",
    sortNameAsc: "Název A - Z",
    sortNameDesc: "Název Z - A",
    sortDateAsc: "Datum ↑",
    sortDateDesc: "Datum ↓",
    sortSizeAsc: "Velikost ↑",
    sortSizeDesc: "Velikost ↓",
    generatorLabel: "GENEROVAT",
    generatorItem: "Položek: {count}",
    generatorModeAll: "Generátor: všechny",
    generatorModeVisible: "Generátor: pouze viditelné",
    minimizeBtn: "Minimalizovat rozhraní",
    maximizeBtn: "Obnovit rozhraní",
    viewModeFull: "Zobrazení: Obaly a text",
    viewModeImage: "Zobrazení: Pouze obaly",
    viewModeText: "Zobrazení: Pouze text",
    orientationFilterAll: "Zobrazit vše",
    orientationFilterVert: "Zobrazit pouze svislé",
    orientationFilterHoriz: "Zobrazit pouze vodorovné",
    themeBtn: "Tmavý / Světlý režim",
    sizeLabel: "Velikost miniatur",
    rowsLabel: "Počet řádků",
    playBtn: "Spustit prezentaci",
    guideInfoFormat: "Formát",
    guideInfoSize: "Velikost",
    guideBtnOpen: "Otevřít",
    guideBtnView: "Zobrazit",
    guideBtnDownload: "Stáhnout",
    paginationFirst: "První strana",
    paginationPrev: "Předchozí strana",
    paginationNext: "Další strana",
    paginationLast: "Poslední strana",
    paginationReset: "Přejít na první stranu",
    paginationCarouselStart: "Povolit automatické posouvání",
    paginationCarouselStop: "Zastavit automatické posouvání",
    mainResetBtn: "Resetovat zobrazení",
    btnVideo: "Video",
    videoBtnPrev: "Předchozí video",
    videoBtnPlay: "Přehrát",
    videoBtnPause: "Pauza",
    videoBtnOff: "Vypnout video",
    videoBtnShuffle: "Náhodné video Zap/Vyp",
    videoBtnNext: "Další video",
    videoBtnReset: "Resetovat nastavení videa",
    footerDate: "© 2025-10-03",
    footerDesc: "pro katalogizaci, správu a prezentaci souborů a složek",
    footerIdleTime: "Nečinnost",
    footerSessionTime: "Relace",
    privacyTitle: "Respektujeme vaše soukromí",
    privacyDesc: "Žádné cookies ani sledování.",
    privacySafe: "Čistý a bezpečný kód!",
    fullscreenBtn: "Celá obrazovka",
    fullscreenExitBtn: "Ukončit celou obrazovku",
    closeBtn: "Zavřít",
    lightboxFxBtn: "Přechodové efekty Zap/Vyp",
    lightboxVideoOptions: "Rozbalit možnosti videa",
    lightboxLabelsBtn: "Zobrazit/skrýt štítky",
    slideshowFirst: "První",
    slideshowPrev: "Předchozí",
    slideshowStop: "Stop",
    slideshowPlayPause: "Play/Pauza",
    slideshowShuffle: "Náhodné snímky Zap/Vyp",
    slideshowNext: "Další",
    slideshowLast: "Poslední",
    guideTagsLabel: "Štítky",
    moonPhaseNames: [
      "Nov",
      "Dorůstající srpek",
      "První čtvrť",
      "Dorůstající měsíc",
      "Úplněk",
      "Couvající měsíc",
      "Poslední čtvrť",
      "Ubývající srpek",
    ],
  },
  // Slovak
  sk: {
    pageTitle: "ŠTART ▪ maxi MENU ▪",
    guideCounter: "Položiek: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Žiadne položky na generovanie!",
    btnBack: "Späť",
    btnLoad: "Načítať...",
    searchPlaceholder: "Hľadať položky...",
    filterAll: "FILTER",
    sortLabel: "ZORADIŤ",
    sortShuffle: "Zamiešať",
    sortNameAsc: "Názov A - Z",
    sortNameDesc: "Názov Z - A",
    sortDateAsc: "Dátum ↑",
    sortDateDesc: "Dátum ↓",
    sortSizeAsc: "Veľkosť ↑",
    sortSizeDesc: "Veľkosť ↓",
    generatorLabel: "GENEROVAŤ",
    generatorItem: "Položiek: {count}",
    generatorModeAll: "Generátor: všetky",
    generatorModeVisible: "Generátor: iba viditeľné",
    minimizeBtn: "Minimalizovať rozhranie",
    maximizeBtn: "Obnoviť rozhranie",
    viewModeFull: "Zobrazenie: Obaly a text",
    viewModeImage: "Zobrazenie: Iba obaly",
    viewModeText: "Zobrazenie: Iba text",
    orientationFilterAll: "Zobraziť všetko",
    orientationFilterVert: "Zobraziť iba zvislé",
    orientationFilterHoriz: "Zobraziť iba vodorovné",
    themeBtn: "Tmavý / Svetlý režim",
    sizeLabel: "Veľkosť miniatúr",
    rowsLabel: "Počet riadkov",
    playBtn: "Spustiť prezentáciu",
    guideInfoFormat: "Formát",
    guideInfoSize: "Veľkosť",
    guideBtnOpen: "Otvoriť",
    guideBtnView: "Zobraziť",
    guideBtnDownload: "Stiahnuť",
    paginationFirst: "Prvá strana",
    paginationPrev: "Predchádzajúca strana",
    paginationNext: "Nasledujúca strana",
    paginationLast: "Posledná strana",
    paginationReset: "Ísť na prvú stranu",
    paginationCarouselStart: "Povoliť automatické posúvanie",
    paginationCarouselStop: "Zastaviť automatické posúvanie",
    mainResetBtn: "Resetovať zobrazenie",
    btnVideo: "Video",
    videoBtnPrev: "Predchádzajúce video",
    videoBtnPlay: "Prehrať",
    videoBtnPause: "Pauza",
    videoBtnOff: "Vypnúť video",
    videoBtnShuffle: "Náhodné video Zap/Vyp",
    videoBtnNext: "Ďalšie video",
    videoBtnReset: "Resetovať nastavenia videa",
    footerDate: "© 2025-10-03",
    footerDesc: "na katalogizáciu, správu a prezentáciu súborov a priečinkov",
    footerIdleTime: "Nečinnosť",
    footerSessionTime: "Relácia",
    privacyTitle: "Rešpektujeme vaše súkromie",
    privacyDesc: "Žiadne cookies ani sledovanie.",
    privacySafe: "Čistý a bezpečný kód!",
    fullscreenBtn: "Celá obrazovka",
    fullscreenExitBtn: "Ukončiť celú obrazovku",
    closeBtn: "Zavrieť",
    lightboxFxBtn: "Prechodové efekty Zap/Vyp",
    lightboxVideoOptions: "Rozbaliť možnosti videa",
    lightboxLabelsBtn: "Zobraziť/skryť štítky",
    slideshowFirst: "Prvý",
    slideshowPrev: "Predchádzajúci",
    slideshowStop: "Stop",
    slideshowPlayPause: "Play/Pauza",
    slideshowShuffle: "Náhodné snímky Zap/Vyp",
    slideshowNext: "Ďalší",
    slideshowLast: "Posledný",
    guideTagsLabel: "Značky",
    moonPhaseNames: [
      "Nov",
      "Pribúdajúci kosáčik",
      "Prvá štvrť",
      "Pribúdajúci mesiac",
      "Spln",
      "Ubúdajúci mesiac",
      "Posledná štvrť",
      "Ubúdajúci kosáčik",
    ],
  },
  // Ukrainian
  uk: {
    pageTitle: "СТАРТ ▪ maxi МЕНЮ ▪",
    guideCounter: "Елементів: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Немає елементів для генерації!",
    btnBack: "Назад",
    btnLoad: "Завантажити...",
    searchPlaceholder: "Пошук елементів...",
    filterAll: "ФІЛЬТР",
    sortLabel: "СОРТУВАТИ",
    sortShuffle: "Перемішати",
    sortNameAsc: "Назва А - Я",
    sortNameDesc: "Назва Я - А",
    sortDateAsc: "Дата ↑",
    sortDateDesc: "Дата ↓",
    sortSizeAsc: "Розмір ↑",
    sortSizeDesc: "Розмір ↓",
    generatorLabel: "ГЕНЕРУВАТИ",
    generatorItem: "Елементів: {count}",
    generatorModeAll: "Генератор: всі",
    generatorModeVisible: "Генератор: тільки видимі",
    minimizeBtn: "Згорнути інтерфейс",
    maximizeBtn: "Відновити інтерфейс",
    viewModeFull: "Вигляд: Обкладинки та текст",
    viewModeImage: "Вигляд: Тільки обкладинки",
    viewModeText: "Вигляд: Тільки текст",
    orientationFilterAll: "Показати всі",
    orientationFilterVert: "Показати тільки вертикальні",
    orientationFilterHoriz: "Показати тільки горизонтальні",
    themeBtn: "Темний / Світлий режим",
    sizeLabel: "Розмір мініатюр",
    rowsLabel: "Кількість рядків",
    playBtn: "Почати слайд-шоу",
    guideInfoFormat: "Формат",
    guideInfoSize: "Розмір",
    guideBtnOpen: "Відкрити",
    guideBtnView: "Переглянути",
    guideBtnDownload: "Завантажити",
    paginationFirst: "Перша сторінка",
    paginationPrev: "Попередня сторінка",
    paginationNext: "Наступна сторінка",
    paginationLast: "Остання сторінка",
    paginationReset: "На першу сторінку",
    paginationCarouselStart: "Увімкнути автопрокрутку",
    paginationCarouselStop: "Зупинити автопрокрутку",
    mainResetBtn: "Скинути вигляд",
    btnVideo: "Відео",
    videoBtnPrev: "Попереднє відео",
    videoBtnPlay: "Відтворити",
    videoBtnPause: "Пауза",
    videoBtnOff: "Вимкнути відео",
    videoBtnShuffle: "Випадкове відео Увімк/Вимк",
    videoBtnNext: "Наступне відео",
    videoBtnReset: "Скинути налаштування відео",
    footerDate: "© 2025-10-03",
    footerDesc: "для каталогізації, керування та презентації файлів і папок",
    footerIdleTime: "Бездіяльність",
    footerSessionTime: "Сесія",
    privacyTitle: "Ми поважаємо вашу конфіденційність",
    privacyDesc: "Без файлів cookie та відстеження.",
    privacySafe: "Чистий та безпечний код!",
    fullscreenBtn: "Повноекранний режим",
    fullscreenExitBtn: "Вийти з повноекранного режиму",
    closeBtn: "Закрити",
    lightboxFxBtn: "Ефекти переходу Увімк/Вимк",
    lightboxVideoOptions: "Розгорнути опції відео",
    lightboxLabelsBtn: "Показати/сховати мітки",
    slideshowFirst: "Перший",
    slideshowPrev: "Попередній",
    slideshowStop: "Стоп",
    slideshowPlayPause: "Play/Пауза",
    slideshowShuffle: "Випадкові слайди Увімк/Вимк",
    slideshowNext: "Наступний",
    slideshowLast: "Останній",
    guideTagsLabel: "Теги",
    moonPhaseNames: [
      "Новий місяць",
      "Молодий місяць",
      "Перша чверть",
      "Зростаючий місяць",
      "Повня",
      "Спадаючий місяць",
      "Остання чверть",
      "Старий місяць",
    ],
  },
  // Indonesian
  id: {
    pageTitle: "MULAI ▪ maxi MENU ▪",
    guideCounter: "Item: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Tidak ada item untuk dibuat!",
    btnBack: "Kembali",
    btnLoad: "Muat...",
    searchPlaceholder: "Cari item...",
    filterAll: "FILTER",
    sortLabel: "URUTKAN",
    sortShuffle: "Acak",
    sortNameAsc: "Nama A - Z",
    sortNameDesc: "Nama Z - A",
    sortDateAsc: "Tanggal ↑",
    sortDateDesc: "Tanggal ↓",
    sortSizeAsc: "Ukuran ↑",
    sortSizeDesc: "Ukuran ↓",
    generatorLabel: "HASILKAN",
    generatorItem: "Item: {count}",
    generatorModeAll: "Generator: semua",
    generatorModeVisible: "Generator: hanya yang terlihat",
    minimizeBtn: "Minimalkan antarmuka",
    maximizeBtn: "Pulihkan antarmuka",
    viewModeFull: "Tampilan: Sampul dan teks",
    viewModeImage: "Tampilan: Hanya sampul",
    viewModeText: "Tampilan: Hanya teks",
    orientationFilterAll: "Tampilkan semua",
    orientationFilterVert: "Tampilkan vertikal saja",
    orientationFilterHoriz: "Tampilkan horizontal saja",
    themeBtn: "Mode Gelap / Terang",
    sizeLabel: "Ukuran thumbnail",
    rowsLabel: "Jumlah baris",
    playBtn: "Mulai tayangan slide",
    guideInfoFormat: "Format",
    guideInfoSize: "Ukuran",
    guideBtnOpen: "Buka",
    guideBtnView: "Lihat",
    guideBtnDownload: "Unduh",
    paginationFirst: "Halaman pertama",
    paginationPrev: "Halaman sebelumnya",
    paginationNext: "Halaman berikutnya",
    paginationLast: "Halaman terakhir",
    paginationReset: "Ke halaman pertama",
    paginationCarouselStart: "Aktifkan gulir otomatis",
    paginationCarouselStop: "Hentikan gulir otomatis",
    mainResetBtn: "Atur ulang tampilan",
    btnVideo: "Video",
    videoBtnPrev: "Video sebelumnya",
    videoBtnPlay: "Putar",
    videoBtnPause: "Jeda",
    videoBtnOff: "Matikan video",
    videoBtnShuffle: "Video acak Nyala/Mati",
    videoBtnNext: "Video berikutnya",
    videoBtnReset: "Atur ulang pengaturan video",
    footerDate: "© 2025-10-03",
    footerDesc:
      "untuk katalogisasi, pengelolaan, dan presentasi file dan folder",
    footerIdleTime: "Diam",
    footerSessionTime: "Sesi",
    privacyTitle: "Kami menghargai privasi Anda",
    privacyDesc: "Tidak ada cookie atau pelacakan.",
    privacySafe: "Kode bersih dan aman!",
    fullscreenBtn: "Layar penuh",
    fullscreenExitBtn: "Keluar dari layar penuh",
    closeBtn: "Tutup",
    lightboxFxBtn: "Efek transisi Nyala/Mati",
    lightboxVideoOptions: "Perluas opsi video",
    lightboxLabelsBtn: "Tampilkan/sembunyikan label",
    slideshowFirst: "Pertama",
    slideshowPrev: "Sebelumnya",
    slideshowStop: "Berhenti",
    slideshowPlayPause: "Putar/Jeda",
    slideshowShuffle: "Slide acak Nyala/Mati",
    slideshowNext: "Berikutnya",
    slideshowLast: "Terakhir",
    guideTagsLabel: "Tag",
    moonPhaseNames: [
      "Bulan Baru",
      "Sabit Awal",
      "Kuartal Pertama",
      "Cembung Awal",
      "Bulan Purnama",
      "Cembung Akhir",
      "Kuartal Ketiga",
      "Sabit Akhir",
    ],
  },
  // Hindi
  hi: {
    pageTitle: "शुरू ▪ मैक्सी मेनू ▪",
    guideCounter: "आइटम: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "उत्पन्न करने के लिए कोई आइटम नहीं!",
    btnBack: "वापस",
    btnLoad: "लोड...",
    searchPlaceholder: "आइटम खोजें...",
    filterAll: "फ़िल्टर",
    sortLabel: "क्रमबद्ध",
    sortShuffle: "शफ़ल",
    sortNameAsc: "नाम A - Z",
    sortNameDesc: "नाम Z - A",
    sortDateAsc: "दिनांक ↑",
    sortDateDesc: "दिनांक ↓",
    sortSizeAsc: "आकार ↑",
    sortSizeDesc: "आकार ↓",
    generatorLabel: "उत्पन्न",
    generatorItem: "आइटम: {count}",
    generatorModeAll: "जेनरेटर: सभी",
    generatorModeVisible: "जेनरेटर: केवल दृश्यमान",
    minimizeBtn: "इंटरफ़ेस छोटा करें",
    maximizeBtn: "इंटरफ़ेस पुनर्स्थापित करें",
    viewModeFull: "दृश्य: कवर और टेक्स्ट",
    viewModeImage: "दृश्य: केवल कवर",
    viewModeText: "दृश्य: केवल टेक्स्ट",
    orientationFilterAll: "सभी दिखाएँ",
    orientationFilterVert: "केवल वर्टिकल दिखाएँ",
    orientationFilterHoriz: "केवल हॉरिजॉन्टल दिखाएँ",
    themeBtn: "डार्क / लाइट मोड",
    sizeLabel: "थंबनेल का आकार",
    rowsLabel: "पंक्तियों की संख्या",
    playBtn: "स्लाइड शो शुरू करें",
    guideInfoFormat: "प्रारूप",
    guideInfoSize: "आकार",
    guideBtnOpen: "खोलें",
    guideBtnView: "देखें",
    guideBtnDownload: "डाउनलोड",
    paginationFirst: "पहला पृष्ठ",
    paginationPrev: "पिछला पृष्ठ",
    paginationNext: "अगला पृष्ठ",
    paginationLast: "अंतिम पृष्ठ",
    paginationReset: "पहले पृष्ठ पर जाएँ",
    paginationCarouselStart: "ऑटो-स्क्रॉल सक्षम करें",
    paginationCarouselStop: "ऑटो-स्क्रॉल रोकें",
    mainResetBtn: "दृश्य रीसेट करें",
    btnVideo: "वीडियो",
    videoBtnPrev: "पिछला वीडियो",
    videoBtnPlay: "चलाएँ",
    videoBtnPause: "रोकें",
    videoBtnOff: "वीडियो बंद करें",
    videoBtnShuffle: "वीडियो शफ़ल चालू/बंद",
    videoBtnNext: "अगला वीडियो",
    videoBtnReset: "वीडियो सेटिंग्स रीसेट करें",
    footerDate: "© 2025-10-03",
    footerDesc:
      "फ़ाइलों और फ़ोल्डरों की कैटलॉगिंग, प्रबंधन और प्रस्तुति के लिए",
    footerIdleTime: "निष्क्रिय",
    footerSessionTime: "सत्र",
    privacyTitle: "हम आपकी गोपनीयता का सम्मान करते हैं",
    privacyDesc: "कोई कुकीज़ या ट्रैकिंग नहीं।",
    privacySafe: "साफ और सुरक्षित कोड!",
    fullscreenBtn: "फ़ुलस्क्रीन",
    fullscreenExitBtn: "फ़ुलस्क्रीन से बाहर निकलें",
    closeBtn: "बंद करें",
    lightboxFxBtn: "संक्रमण प्रभाव चालू/बंद",
    lightboxVideoOptions: "वीडियो विकल्प विस्तृत करें",
    lightboxLabelsBtn: "लेबल दिखाएँ/छिपाएँ",
    slideshowFirst: "पहला",
    slideshowPrev: "पिछला",
    slideshowStop: "रोकें",
    slideshowPlayPause: "चलाएँ/रोकें",
    slideshowShuffle: "स्लाइड शफ़ल चालू/बंद",
    slideshowNext: "अगला",
    slideshowLast: "अंतिम",
    guideTagsLabel: "टैग",
    moonPhaseNames: [
      "अमावस्या",
      "बालचंद्र",
      "प्रथम चौथाई",
      "वृद्धिशील गिबस",
      "पूर्णिमा",
      "क्षयकारी गिबस",
      "अंतिम चौथाई",
      "क्षयकारी वर्धमान",
    ],
  },
  us: {
    pageTitle: "START ▪ maxi MENU ▪",
    guideCounter: "Items: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "No items to generate!",
    btnBack: "Back",
    btnLoad: "Load...",
    searchPlaceholder: "Search items...",
    filterAll: "FILTER",
    sortLabel: "SORT",
    sortShuffle: "Shuffle",
    sortNameAsc: "Name A - Z",
    sortNameDesc: "Name Z - A",
    sortDateAsc: "Date ↑",
    sortDateDesc: "Date ↓",
    sortSizeAsc: "Size ↑",
    sortSizeDesc: "Size ↓",
    generatorLabel: "GENERATE",
    generatorItem: "Items: {count}",
    generatorModeAll: "Generator: full pool",
    generatorModeVisible: "Generator: visible only",
    minimizeBtn: "Minimize interface",
    maximizeBtn: "Restore interface",
    viewModeFull: "View: Covers and text",
    viewModeImage: "View: Covers only",
    viewModeText: "View: Text only",
    orientationFilterAll: "Show all",
    orientationFilterVert: "Show vertical only",
    orientationFilterHoriz: "Show horizontal only",
    themeBtn: "Dark / Light mode",
    sizeLabel: "Thumbnail size",
    rowsLabel: "Number of rows",
    playBtn: "Start slideshow",
    guideInfoFormat: "Format",
    guideInfoSize: "Size",
    guideBtnOpen: "Open",
    guideBtnView: "View",
    guideBtnDownload: "Download",
    paginationFirst: "First page",
    paginationPrev: "Previous page",
    paginationNext: "Next page",
    paginationLast: "Last page",
    paginationReset: "Go to first page",
    paginationCarouselStart: "Enable auto-scroll",
    paginationCarouselStop: "Stop auto-scroll",
    mainResetBtn: "Reset view",
    btnVideo: "Video",
    videoBtnPrev: "Previous video",
    videoBtnPlay: "Play",
    videoBtnPause: "Pause",
    videoBtnOff: "Turn off video",
    videoBtnShuffle: "Shuffle video On/Off",
    videoBtnNext: "Next video",
    videoBtnReset: "Reset video settings",
    footerDate: "© 2025-10-03",
    footerDesc: "for cataloging, managing and presenting files and folders",
    footerIdleTime: "Idle",
    footerSessionTime: "Session",
    privacyTitle: "We respect your privacy",
    privacyDesc: "No cookies or tracking.",
    privacySafe: "Clean and safe code!",
    fullscreenBtn: "Fullscreen",
    fullscreenExitBtn: "Exit fullscreen",
    closeBtn: "Close",
    lightboxFxBtn: "Transition effects On/Off",
    lightboxVideoOptions: "Expand video options",
    lightboxLabelsBtn: "Show/hide labels",
    slideshowFirst: "First",
    slideshowPrev: "Previous",
    slideshowStop: "Stop",
    slideshowPlayPause: "Play/Pause",
    slideshowShuffle: "Shuffle slides On/Off",
    slideshowNext: "Next",
    slideshowLast: "Last",
    guideTagsLabel: "Tags",
    moonPhaseNames: [
      "New Moon",
      "Waxing Crescent",
      "First Quarter",
      "Waxing Gibbous",
      "Full Moon",
      "Waning Gibbous",
      "Last Quarter",
      "Waning Crescent",
    ],
  },
  sg: {
    pageTitle: "START ▪ maxi MENU ▪",
    guideCounter: "Items: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "No items to generate!",
    btnBack: "Back",
    btnLoad: "Load...",
    searchPlaceholder: "Search items...",
    filterAll: "FILTER",
    sortLabel: "SORT",
    sortShuffle: "Shuffle",
    sortNameAsc: "Name A - Z",
    sortNameDesc: "Name Z - A",
    sortDateAsc: "Date ↑",
    sortDateDesc: "Date ↓",
    sortSizeAsc: "Size ↑",
    sortSizeDesc: "Size ↓",
    generatorLabel: "GENERATE",
    generatorItem: "Items: {count}",
    generatorModeAll: "Generator: full pool",
    generatorModeVisible: "Generator: visible only",
    minimizeBtn: "Minimize interface",
    maximizeBtn: "Restore interface",
    viewModeFull: "View: Covers and text",
    viewModeImage: "View: Covers only",
    viewModeText: "View: Text only",
    orientationFilterAll: "Show all",
    orientationFilterVert: "Show vertical only",
    orientationFilterHoriz: "Show horizontal only",
    themeBtn: "Dark / Light mode",
    sizeLabel: "Thumbnail size",
    rowsLabel: "Number of rows",
    playBtn: "Start slideshow",
    guideInfoFormat: "Format",
    guideInfoSize: "Size",
    guideBtnOpen: "Open",
    guideBtnView: "View",
    guideBtnDownload: "Download",
    paginationFirst: "First page",
    paginationPrev: "Previous page",
    paginationNext: "Next page",
    paginationLast: "Last page",
    paginationReset: "Go to first page",
    paginationCarouselStart: "Enable auto-scroll",
    paginationCarouselStop: "Stop auto-scroll",
    mainResetBtn: "Reset view",
    btnVideo: "Video",
    videoBtnPrev: "Previous video",
    videoBtnPlay: "Play",
    videoBtnPause: "Pause",
    videoBtnOff: "Turn off video",
    videoBtnShuffle: "Shuffle video On/Off",
    videoBtnNext: "Next video",
    videoBtnReset: "Reset video settings",
    footerDate: "© 2025-10-03",
    footerDesc: "for cataloging, managing and presenting files and folders",
    footerIdleTime: "Idle",
    footerSessionTime: "Session",
    privacyTitle: "We respect your privacy",
    privacyDesc: "No cookies or tracking.",
    privacySafe: "Clean and safe code!",
    fullscreenBtn: "Fullscreen",
    fullscreenExitBtn: "Exit fullscreen",
    closeBtn: "Close",
    lightboxFxBtn: "Transition effects On/Off",
    lightboxVideoOptions: "Expand video options",
    lightboxLabelsBtn: "Show/hide labels",
    slideshowFirst: "First",
    slideshowPrev: "Previous",
    slideshowStop: "Stop",
    slideshowPlayPause: "Play/Pause",
    slideshowShuffle: "Shuffle slides On/Off",
    slideshowNext: "Next",
    slideshowLast: "Last",
    guideTagsLabel: "Tags",
    moonPhaseNames: [
      "New Moon",
      "Waxing Crescent",
      "First Quarter",
      "Waxing Gibbous",
      "Full Moon",
      "Waning Gibbous",
      "Last Quarter",
      "Waning Crescent",
    ],
  },
  tr: {
    pageTitle: "BAŞLAT ▪ maxi MENÜ ▪",
    guideCounter: "Öğe: <b>{count}</b> / {total}",
    statusBarSeparator: "|",
    alertNoItems: "Oluşturulacak öğe yok!",
    btnBack: "Geri",
    btnLoad: "Yükle...",
    searchPlaceholder: "Öğeleri ara...",
    filterAll: "FİLTRE",
    sortLabel: "SIRALA",
    sortShuffle: "Karıştır",
    sortNameAsc: "Ad A - Z",
    sortNameDesc: "Ad Z - A",
    sortDateAsc: "Tarih ↑",
    sortDateDesc: "Tarih ↓",
    sortSizeAsc: "Boyut ↑",
    sortSizeDesc: "Boyut ↓",
    generatorLabel: "OLUŞTUR",
    generatorItem: "Öğe: {count}",
    generatorModeAll: "Oluşturucu: tüm havuz",
    generatorModeVisible: "Oluşturucu: sadece görünür",
    minimizeBtn: "Arayüzü simge durumuna küçült",
    maximizeBtn: "Arayüzü geri yükle",
    viewModeFull: "Görünüm: Kapaklar ve metin",
    viewModeImage: "Görünüm: Sadece kapaklar",
    viewModeText: "Görünüm: Sadece metin",
    orientationFilterAll: "Tümünü göster",
    orientationFilterVert: "Yalnızca dikey olanları göster",
    orientationFilterHoriz: "Yalnızca yatay olanları göster",
    themeBtn: "Karanlık / Aydınlık mod",
    sizeLabel: "Küçük resim boyutu",
    rowsLabel: "Satır sayısı",
    playBtn: "Slayt gösterisini başlat",
    guideInfoFormat: "Format",
    guideInfoSize: "Boyut",
    guideBtnOpen: "Aç",
    guideBtnView: "Görüntüle",
    guideBtnDownload: "İndir",
    paginationFirst: "İlk sayfa",
    paginationPrev: "Önceki sayfa",
    paginationNext: "Sonraki sayfa",
    paginationLast: "Son sayfa",
    paginationReset: "İlk sayfaya git",
    paginationCarouselStart: "Otomatik kaydırmayı etkinleştir",
    paginationCarouselStop: "Otomatik kaydırmayı durdur",
    mainResetBtn: "Görünümü sıfırla",
    btnVideo: "Video",
    videoBtnPrev: "Önceki video",
    videoBtnPlay: "Oynat",
    videoBtnPause: "Duraklat",
    videoBtnOff: "Videoyu kapat",
    videoBtnShuffle: "Videoyu karıştır Açık/Kapalı",
    videoBtnNext: "Sonraki video",
    videoBtnReset: "Video ayarlarını sıfırla",
    footerDate: "© 2025-10-03",
    footerDesc: "dosya ve klasörleri kataloglamak, yönetmek ve sunmak için",
    footerIdleTime: "Boşta",
    footerSessionTime: "Oturum",
    privacyTitle: "Gizliliğinize saygı duyuyoruz",
    privacyDesc: "Çerez veya izleme yok.",
    privacySafe: "Temiz ve güvenli kod!",
    fullscreenBtn: "Tam ekran",
    fullscreenExitBtn: "Tam ekrandan çık",
    closeBtn: "Kapat",
    lightboxFxBtn: "Geçiş efektleri Açık/Kapalı",
    lightboxVideoOptions: "Video seçeneklerini genişlet",
    lightboxLabelsBtn: "Etiketleri göster/gizle",
    slideshowFirst: "İlk",
    slideshowPrev: "Önceki",
    slideshowStop: "Durdur",
    slideshowPlayPause: "Oynat/Duraklat",
    slideshowShuffle: "Slaytları karıştır Açık/Kapalı",
    slideshowNext: "Sonraki",
    slideshowLast: "Son",
    guideTagsLabel: "Etiketler",
    moonPhaseNames: [
      "Yeni Ay",
      "Hilal",
      "İlk Dördün",
      "Büyüyen Kambur",
      "Dolunay",
      "Küçülen Kambur",
      "Son Dördün",
      "Balzamik Ay",
    ],
  },
};