const languageStrings = {
    pl: {
        pageTitle: "START ▪ maxi MENU ▪",
        guideCounter: "<b>{count}</b> / {total} pozycji",
        statusBarSeparator: "|",
        alertNoItems: "Brak pozycji do wygenerowania!",
        btnBack: "Wstecz",
        btnLoad: "Załaduj...",
        searchPlaceholder: "Szukaj pozycji...",
        filterAll: "FILTR",
        sortLabel: "SORTUJ",
        sortShuffle: "Wymieszaj",
        sortNameAsc: "Nazwa A - Z",
        sortNameDesc: "Nazwa Z - A",
        sortDateAsc: "Data ↑",
        sortDateDesc: "Data ↓",
        sortSizeAsc: "Rozmiar ↑",
        sortSizeDesc: "Rozmiar ↓",
        generatorLabel: "LOSUJ",
        generatorItem: "Pozycji: {count}",
        generatorModeAll: "Generator: cała pula",
        generatorModeVisible: "Generator: tylko widoczne",
        minimizeBtn: "Minimalizuj interfejs",
        maximizeBtn: "Przywróć interfejs",
        viewModeFull: "Widok: Okładki i tekst",
        viewModeImage: "Widok: Tylko okładki",
        viewModeText: "Widok: Tylko tekst",
        orientationFilterAll: "Pokaż wszystkie",
        orientationFilterVert: "Pokaż tylko pionowe",
        orientationFilterHoriz: "Pokaż tylko poziome",
        themeBtn: "Tryb Ciemny / Jasny",
        sizeLabel: "Wielkość miniaturek",
        rowsLabel: "Liczba wierszy",
        playBtn: "Rozpocznij pokaz",
        guideInfoFormat: "Format",
        guideInfoSize: "Rozmiar",
        guideBtnOpen: "Otwórz",
        guideBtnView: "Zobacz",
        guideBtnDownload: "Pobierz",
        paginationFirst: "Pierwsza strona",
        paginationPrev: "Poprzednia strona",
        paginationNext: "Następna strona",
        paginationLast: "Ostatnia strona",
        paginationReset: "Przejdź do pierwszej strony",
        paginationCarouselStart: "Włącz automatyczne przewijanie",
        paginationCarouselStop: "Zatrzymaj automatyczne przewijanie",
        mainResetBtn: "Resetuj widok",
        btnVideo: "Wideo",
        videoBtnPrev: "Poprzednie wideo",
        videoBtnPlay: "Odtwarzaj",
        videoBtnPause: "Pauza",
        videoBtnOff: "Wyłącz wideo",
        videoBtnShuffle: "Losowe wideo Wł/Wył",
        videoBtnNext: "Następne wideo",
        videoBtnReset: "Resetuj ustawienia wideo",
        footerDate: "© 2025-09-17",
        footerDesc: "do katalogowania, zarządzania i prezentacji plików i folderów",
        footerIdleTime: "Bezczynność",
        footerSessionTime: "Sesja",
        privacyTitle: "Szanujemy Twoją prywatność",
        privacyDesc: "Żadnych ciasteczek ani śledzenia.",
        privacySafe: "Czysty i bezpieczny kod!",
        fullscreenBtn: "Pełny ekran",
        fullscreenExitBtn: "Wyjdź z pełnego ekranu",
        closeBtn: "Zamknij",
        lightboxFxBtn: "Animacje przejść Wł/Wył",
        lightboxVideoOptions: "Rozwiń opcje wideo",
        lightboxLabelsBtn: "Pokaż/ukryj etykiety",
        slideshowFirst: "Pierwszy",
        slideshowPrev: "Poprzedni",
        slideshowStop: "Zatrzymaj",
        slideshowPlayPause: "Play/Pauza",
        slideshowShuffle: "Losowe slajdy Wł/Wył",
        slideshowNext: "Następny",
        slideshowLast: "Ostatni",
    },
    en: {
        pageTitle: "START ▪ maxi MENU ▪",
        guideCounter: "<b>{count}</b> / {total} items",
        statusBarSeparator: "|",
        alertNoItems: "No items to generate!",
        btnBack: "Back",
        btnLoad: "Load...",
        searchPlaceholder: "Search items...",
        filterAll: "FILTER",
        sortLabel: "SORT",
        sortShuffle: "Shuffle",
        sortNameAsc: "Name A - Z",
        sortNameDesc: "Name Z - A",
        sortDateAsc: "Date ↑",
        sortDateDesc: "Date ↓",
        sortSizeAsc: "Size ↑",
        sortSizeDesc: "Size ↓",
        generatorLabel: "GENERATE",
        generatorItem: "Items: {count}",
        generatorModeAll: "Generator: full pool",
        generatorModeVisible: "Generator: visible only",
        minimizeBtn: "Minimize interface",
        maximizeBtn: "Restore interface",
        viewModeFull: "View: Covers and text",
        viewModeImage: "View: Covers only",
        viewModeText: "View: Text only",
        orientationFilterAll: "Show all",
        orientationFilterVert: "Show vertical only",
        orientationFilterHoriz: "Show horizontal only",
        themeBtn: "Dark / Light mode",
        sizeLabel: "Thumbnail size",
        rowsLabel: "Number of rows",
        playBtn: "Start slideshow",
        guideInfoFormat: "Format",
        guideInfoSize: "Size",
        guideBtnOpen: "Open",
        guideBtnView: "View",
        guideBtnDownload: "Download",
        paginationFirst: "First page",
        paginationPrev: "Previous page",
        paginationNext: "Next page",
        paginationLast: "Last page",
        paginationReset: "Go to first page",
        paginationCarouselStart: "Enable auto-scroll",
        paginationCarouselStop: "Stop auto-scroll",
        mainResetBtn: "Reset view",
        btnVideo: "Video",
        videoBtnPrev: "Previous video",
        videoBtnPlay: "Play",
        videoBtnPause: "Pause",
        videoBtnOff: "Turn off video",
        videoBtnShuffle: "Shuffle video On/Off",
        videoBtnNext: "Next video",
        videoBtnReset: "Reset video settings",
        footerDate: "© 2025-09-17",
        footerDesc: "for cataloging, managing and presenting files and folders",
        footerIdleTime: "Idle",
        footerSessionTime: "Session",
        privacyTitle: "We respect your privacy",
        privacyDesc: "No cookies or tracking.",
        privacySafe: "Clean and safe code!",
        fullscreenBtn: "Fullscreen",
        fullscreenExitBtn: "Exit fullscreen",
        closeBtn: "Close",
        lightboxFxBtn: "Transition effects On/Off",
        lightboxVideoOptions: "Expand video options",
        lightboxLabelsBtn: "Show/hide labels",
        slideshowFirst: "First",
        slideshowPrev: "Previous",
        slideshowStop: "Stop",
        slideshowPlayPause: "Play/Pause",
        slideshowShuffle: "Shuffle slides On/Off",
        slideshowNext: "Next",
        slideshowLast: "Last",
    }
};

