const imageTags = {
  "adrspach-1360069_1920.jpg": ["adrszpach", "skalne miasto", "skały", "natura", "krajobraz", "góry", "czechy", "formacje skalne", "piaskowiec"],
  "apple-juice-2377329_1920.jpg": ["zamek", "krajobraz", "góry", "czechy", "ruiny", "jesień", "mgła", "miasto", "architektura"],
  "apple-juice-5192477_1920.jpg": ["praga", "most karola", "architektura", "rzeka", "wełtawa", "most", "zabytek", "miasto", "historia"],
  "architecture-3716999_1920.jpg": ["ogród", "park", "rzeźba", "natura", "kwiaty", "zieleń", "barok", "architektura"],
  "architecture-5112932_1920.jpg": ["wieża", "ratusz", "zegar", "architektura", "czechy", "historia", "zabytek", "niebo"],
  "baroque-church-3397560_1920.jpg": ["kościół", "barok", "architektura", "czechy", "miasto", "zabytek", "religia", "historia"],
  "books-2253569_1920.jpg": ["książki", "biblioteka", "wiedza", "księgozbiór", "półki", "edukacja", "wnętrze"],
  "books-2253571_1920.jpg": ["książki", "sztuka", "instalacja", "biblioteka", "praga", "tunel", "abstrakcja", "wiedza"],
  "bridge-3481276_1920.jpg": ["praga", "most karola", "panorama", "rzeka", "wełtawa", "miasto", "architektura", "mosty", "krajobraz"],
  "bridges-3337124_1920.jpg": ["praga", "panorama", "mosty", "rzeka", "wełtawa", "most karola", "miasto", "jesień", "architektura"],
  "brno-4335324_1920.jpg": ["brno", "katedra", "kościół", "architektura", "gotyk", "miasto", "zabytek", "panorama", "historia"],
  "brno-4885864_1920.jpg": ["brno", "katedra", "petrov", "kościół", "architektura", "gotyk", "miasto", "chmury", "zabytek"],
  "building-5452900_1920.jpg": ["telcz", "kamienice", "rynek", "renesans", "architektura", "unesco", "miasto", "zabytek", "fasada"],
  "building-7362300_1920.jpg": ["telcz", "kamienice", "rynek", "renesans", "architektura", "unesco", "fasada", "szczyty", "zabytek"],
  "building-924707_1920.jpg": ["architektura", "nowoczesne", "budynki", "osiedle", "miasto", "mieszkania", "urbanistyka"],
  "buildings-6961529_1920.jpg": ["brno", "panorama", "zima", "katedra", "petrov", "miasto", "śnieg", "architektura", "krajobraz"],
  "buildings-6961529_1920(1).jpg": ["brno", "panorama", "zima", "katedra", "petrov", "miasto", "śnieg", "architektura", "krajobraz"],
  "carousel-4680801_1920.jpg": ["diabelski młyn", "karuzela", "wesołe miasteczko", "rozrywka", "miasto", "światła", "detal"],
  "castle-3345329_1920.jpg": ["praga", "hradczany", "most karola", "rzeka", "wełtawa", "zamek", "panorama", "miasto", "kajaki"],
  "castle-3512330_1920.jpg": ["zamek", "cesky sternberk", "architektura", "historia", "forteca", "czechy", "krajobraz", "zabytek"],
  "castle-4069634_1920.jpg": ["zamek", "konopiste", "wieża", "architektura", "czechy", "historia", "park", "zabytek", "romantyzm"],
  "castle-5243048_1920.jpg": ["zamek", "konopiste", "architektura", "czechy", "historia", "park", "drzewa", "zabytek", "biel"],
  "castle-5243146_1920.jpg": ["zamek", "konopiste", "taras", "ogród", "architektura", "czechy", "historia", "park", "rzeźba"],
  "castle-5243465_1920.jpg": ["zamek", "konopiste", "wieża", "architektura", "czechy", "historia", "park", "drzewa", "zabytek"],
  "castle-5243466_1920.jpg": ["zamek", "konopiste", "wieża", "kwiaty", "architektura", "czechy", "historia", "park", "wiosna"],
  "castle-6298938_1920.jpg": ["telcz", "zamek", "jezioro", "odbicie", "panorama", "miasto", "architektura", "unesco", "zmierzch"],
  "castle-972779_1920.jpg": ["zamek", "cervena lhota", "woda", "jezioro", "czerwony", "architektura", "czechy", "odbicie", "historia"],
  "cathedral-5672716_1920.jpg": ["brno", "katedra", "petrov", "kościół", "noc", "oświetlenie", "architektura", "gotyk", "miasto"],
  "cervena-lhota-3232106_1920.jpg": ["zamek", "cervena lhota", "jezioro", "odbicie", "czerwony", "architektura", "czechy", "romantyzm", "natura"],
  "cesky-krumlov-982828_1920.jpg": ["cesky krumlov", "panorama", "miasto", "unesco", "architektura", "dachy", "historia", "rzeka", "zabytek"],
  "chapel-3545156_1920.jpg": ["kaplica", "winnica", "praga", "troja", "architektura", "krajobraz", "wino", "religia", "wzgórze"],
  "church-3340852_1920.jpg": ["kościół", "barok", "architektura", "detal", "fasada", "rzeźby", "sztuka", "historia", "religia"],
  "city-1284436_1920.jpg": ["praga", "hradczany", "zamek", "rzeka", "wełtawa", "panorama", "miasto", "architektura", "mgła"],
  "city-3345873_1920.jpg": ["praga", "panorama", "wyszehrad", "rzeka", "wełtawa", "miasto", "architektura", "mosty", "krajobraz"],
  "city-4708451_1920.jpg": ["praga", "panorama", "wyszehrad", "tory", "pociąg", "miasto", "architektura", "dachy", "zieleń"],
  "city-5080071_1920.jpg": ["miasto", "park", "ścieżka", "budynki", "osiedle", "wiosna", "zieleń", "architektura"],
  "city-5094124_1920.jpg": ["praga", "ulica", "miasto", "architektura", "kamienice", "perspektywa", "samochody", "życie miejskie"],
  "clarion-congress-63999_1280.jpg": ["hotel", "nowoczesna", "architektura", "miasto", "ulica", "budynek", "urbanistyka"],
  "corn-3594240_1920.jpg": ["krajobraz", "pola", "wieś", "natura", "las", "wzgórza", "rolnictwo", "spokój"],
  "country-2865959_1920.jpg": ["krajobraz", "taras", "góry", "park", "pałac", "natura", "jesień", "zieleń", "widok"],
  "country-3520239_1920.jpg": ["krajobraz", "pole", "słup energetyczny", "natura", "wieś", "lato", "zieleń", "energia"],
  "country-4610933_1920.jpg": ["jezioro", "dom", "wieś", "krajobraz", "natura", "woda", "odbicie", "zachód słońca", "spokój"],
  "countryside-3594517_1920.jpg": ["dom", "wieś", "tradycyjny", "architektura", "skansen", "natura", "lato", "sielanka"],
  "czech-4725422_1920.jpg": ["zima", "śnieg", "las", "krajobraz", "góry", "panorama", "natura", "mróz", "błękit"],
  "czech-4725423_1920.jpg": ["zima", "góry", "śnieg", "schronisko", "krajobraz", "turystyka", "szczyt", "mróz"],
  "czech-4725424_1920.jpg": ["zima", "góry", "śnieg", "krajobraz", "panorama", "promienie słońca", "chmury", "natura", "las"],
  "czech-5005383_1920.jpg": ["krajobraz", "góry", "dolina", "mgła", "promienie słońca", "natura", "panorama", "droga", "jesień"],
  "czech-5354055_1920.jpg": ["winnica", "krajobraz", "morawy", "zamek", "ruiny", "wino", "natura", "wiosna", "rolnictwo"],
  "czech-5406632_1920.jpg": ["drzewo", "krajobraz", "natura", "pole", "samotność", "wiosna", "zieleń", "spokój"],
  "czechia-3355591_1920.jpg": ["kościół", "wieża", "gotyk", "architektura", "zabytek", "historia", "religia", "miasto"],
  "czechia-5003794_1920.jpg": ["praga", "kościół", "barok", "św mikołaj", "mała strana", "architektura", "miasto", "zabytek", "kopuła"],
  "czechia-5354033_1920.jpg": ["winnica", "krajobraz", "morawy", "wzgórza", "palava", "wino", "natura", "wiosna", "rolnictwo"],
  "czechia-988734_1920.jpg": ["zamek", "vranov nad dyją", "skała", "architektura", "rzeka", "krajobraz", "historia", "zabytek", "monument"],
  "forest-3092514_1920.jpg": ["dom", "drewniany", "zima", "śnieg", "architektura", "las", "natura", "spokój", "bajkowo"],
  "golf-2683314_1920.jpg": ["golf", "pole golfowe", "sport", "natura", "krajobraz", "trawa", "rekreacja", "zieleń"],
  "gothic-3345648_1920.jpg": ["zamek", "kokorin", "gotyk", "architektura", "wieża", "mur", "historia", "las", "zabytek"],
  "history-2721838_1920.jpg": ["park", "ogród", "zamek", "miasto", "krajobraz", "chmury", "historia", "zieleń", "spokój"],
  "hluboka-nad-vltavou-1313421_1920.jpg": ["zamek", "hluboka", "architektura", "romantyzm", "czechy", "zabytek", "ogród", "bajkowo", "historia"],
  "house-3480405_1920.jpg": ["praga", "kamienica", "architektura", "fasada", "kolor", "miasto", "detal", "bluszcz", "historia"],
  "hradcany-4760609_1920.jpg": ["praga", "hradczany", "katedra św wita", "zamek", "architektura", "gotyk", "panorama", "wiosna", "drzewa"],
  "hradcany-7772871_1920.jpg": ["praga", "most karola", "hradczany", "zamek", "rzeka", "wełtawa", "panorama", "architektura", "miasto"],
  "hydrangea-3512383_1920.jpg": ["kwiaty", "hortensja", "niebieski", "ogród", "natura", "rośliny", "lato", "kolor"],
  "jindrichuv-hradec-4321079_1920.jpg": ["zamek", "jindrichuv hradec", "jezioro", "odbicie", "miasto", "panorama", "architektura", "historia", "czechy"],
  "konopiste-3772527_1920.jpg": ["zamek", "konopiste", "wieża", "architektura", "detal", "historia", "czechy", "zabytek", "romantyzm"],
  "lake-5787323_1920.jpg": ["jezioro", "park", "jesień", "odbicie", "natura", "krajobraz", "woda", "drzewa", "spokój"],
  "liberec-7104563_1920.jpg": ["liberec", "muzeum", "ratusz", "architektura", "historia", "neorenesans", "zabytek", "miasto", "zachód słońca"],
  "metro-3163769_1920.jpg": ["metro", "pociąg", "stacja", "transport", "miasto", "praga", "architektura", "symetria", "tunele"],
  "museum-64013_1920.jpg": ["muzeum", "budynek", "architektura", "miasto", "ulica", "historia", "zabytek", "samochody"],
  "nature-3520727_1920.jpg": ["krajobraz", "dolina", "rzeka", "park narodowy", "podyje", "winnica", "natura", "zieleń", "wzgórza"],
  "nature-7104566_1920.jpg": ["krajobraz", "panorama", "miasto", "liberec", "góry", "jested", "natura", "widok", "niebo"],
  "office-building-745485_1920.jpg": ["architektura", "nowoczesna", "budowa", "beton", "brutalizm", "czarno-białe", "miasto", "budynek"],
  "olomouc-2245991_1920.jpg": ["ołomuniec", "baszta", "mur", "zima", "śnieg", "architektura", "cegła", "historia", "fortyfikacje"],
  "prague-3138732_1920.jpg": ["praga", "most karola", "rzeka", "wełtawa", "łabędzie", "panorama", "miasto", "jesień", "chmury"],
  "prague-3301110_1920.jpg": ["praga", "uliczka", "stare miasto", "nowy świat", "architektura", "bruk", "historia", "spokój", "kamienice"],
  "prague-3520707_1920.jpg": ["praga", "most karola", "hradczany", "rzeka", "wełtawa", "panorama", "miasto", "lato", "spokój"],
  "prague-3582384_1920.jpg": ["praga", "hradczany", "zamek", "rzeka", "wełtawa", "mała strana", "panorama", "miasto", "architektura"],
  "prague-3582399_1920.jpg": ["praga", "most karola", "turyści", "tłum", "wieża mostowa", "miasto", "historia", "architektura", "lato"],
  "prague-3582510_1920.jpg": ["praga", "petrin", "kościół", "panorama", "miasto", "kopuły", "widok", "zieleń", "architektura"],
  "prague-3583231_1920.jpg": ["praga", "hradczany", "katedra św wita", "zamek", "panorama", "miasto", "architektura", "dachy", "gotyk"],
  "prague-3583233_1920.jpg": ["praga", "panorama", "rzeka", "wełtawa", "mosty", "miasto", "architektura", "krajobraz", "widok"],
  "prague-3583236_1920.jpg": ["praga", "panorama", "stare miasto", "mała strana", "rzeka", "wełtawa", "miasto", "dachy", "widok"],
  "prague-3583237_1920.jpg": ["praga", "panorama", "petrin", "obserwatorium", "miasto", "park", "zieleń", "widok", "krajobraz"],
  "prague-3583239_1920.jpg": ["praga", "panorama", "rzeka", "wełtawa", "most karola", "stare miasto", "miasto", "dachy", "historia"],
  "prague-3583241_1920.jpg": ["praga", "panorama", "hradczany", "petrin", "zamek", "miasto", "zieleń", "architektura", "widok"],
  "prague-3584081_1920.jpg": ["praga", "klasztor na strahowie", "strahov", "panorama", "miasto", "architektura", "dachy", "historia", "widok"],
  "prague-3584082_1920.jpg": ["praga", "klasztor na strahowie", "strahov", "panorama", "miasto", "architektura", "historia", "widok", "zieleń"],
  "prague-3584091_1920.jpg": ["praga", "hradczany", "katedra św wita", "zamek", "panorama", "architektura", "gotyk", "miasto", "widok"],
  "prague-3584144_1920.jpg": ["praga", "panorama", "rzeka", "wełtawa", "mosty", "miasto", "architektura", "kamienice", "transport"],
  "prague-3772565_1920.jpg": ["praga", "panorama", "hradczany", "wyszehrad", "rzeka", "wełtawa", "mosty", "miasto", "jesień"],
  "prague-3786829_1920.jpg": ["praga", "kamienice", "architektura", "fasady", "secesja", "historia", "miasto", "ulica", "detale"],
  "prague-3876834_1920.jpg": ["praga", "uliczka", "hradczany", "nowy świat", "architektura", "bruk", "historia", "kamienice", "spokój"],
  "prague-3993226_1920.jpg": ["praga", "panorama", "rzeka", "wełtawa", "mosty", "miasto", "architektura", "zima", "statek"],
  "prague-4060703_1920.jpg": ["praga", "panorama", "kościół św mikołaja", "mała strana", "dachy", "architektura", "barok", "miasto", "widok"],
  "prague-4060705_1920.jpg": ["praga", "teatr narodowy", "rzeka", "wełtawa", "architektura", "miasto", "most", "historia", "kultura"],
  "prague-4060706_1920.jpg": ["praga", "panorama", "kościół św mikołaja", "dachy", "stare miasto", "architektura", "barok", "miasto", "widok"],
  "prague-4060707_1920.jpg": ["praga", "most karola", "hradczany", "rzeka", "wełtawa", "panorama", "miasto", "architektura", "historia"],
  "prague-4378356_1920.jpg": ["praga", "most karola", "noc", "wschód słońca", "latarnie", "architektura", "historia", "spokój", "most"],
  "prague-5101846_1920.jpg": ["praga", "panorama", "wiosna", "zachód słońca", "petrin", "kwitnące drzewa", "miasto", "widok", "romantyzm"],
  "prague-7222431_1920.jpg": ["praga", "stare miasto", "rzeka", "wełtawa", "architektura", "most karola", "historia", "miasto", "widok"],
  "prague-7772872_1920.jpg": ["praga", "hradczany", "katedra św wita", "rzeka", "wełtawa", "mała strana", "panorama", "miasto", "architektura"],
  "prague-961962_1920.jpg": ["praga", "panorama", "most karola", "wieża telewizyjna", "stare miasto", "turyści", "miasto", "rzeka", "wełtawa"],
  "river-3574695_1920.jpg": ["praga", "rzeka", "wełtawa", "statek", "stare miasto", "architektura", "transport", "turystyka", "lato"],
  "river-4708449_1920.jpg": ["praga", "wyszehrad", "rzeka", "wełtawa", "panorama", "kościół", "miasto", "lato", "błękit"],
  "river-4755369_1920.jpg": ["rzeka", "lód", "zima", "las", "natura", "krajobraz", "spokój", "woda", "odbicie"],
  "river-64005_1280.jpg": ["rzeka", "łaba", "krajobraz", "dolina", "miasteczko", "góry", "czechy", "panorama", "woda"],
  "rocks-1360064_1920.jpg": ["adrszpach", "skalne miasto", "skały", "natura", "krajobraz", "góry", "piaskowiec", "wspinaczka", "las"],
  "romanesque-3341789_1920.jpg": ["praga", "wyszehrad", "rotunda", "romański", "architektura", "historia", "kościół", "zabytek", "kamień"],
  "roost-4003340_1920.jpg": ["zamek", "karlstejn", "gotyk", "architektura", "historia", "forteca", "jesień", "las", "czechy"],
  "roost-4954523_1920.jpg": ["zamek", "kasperk", "szumawa", "panorama", "las", "góry", "krajobraz", "historia", "ruiny"],
  "roost-972776_1920.jpg": ["zamek", "kasperk", "szumawa", "las", "góry", "architektura", "historia", "forteca", "jesień"],
  "sazava-3512430_1920.jpg": ["rzeka", "sazava", "krajobraz", "natura", "kajak", "lato", "zieleń", "woda", "spokój"],
  "spolchemie-64014_1920.jpg": ["budynek", "fabryka", "przemysł", "architektura", "modernizm", "usti nad labem", "historia", "praca"],
  "square-4499056_1920.jpg": ["telcz", "rynek", "noc", "kamienice", "renesans", "architektura", "unesco", "bruk", "światła"],
  "street-3480489_1920.jpg": ["praga", "uliczka", "architektura", "mur", "latarnia", "kamienica", "historia", "miasto", "bruk"],
  "teepee-6961710_1920.jpg": ["namiot", "tipi", "zachód słońca", "natura", "kemping", "przygoda", "lato", "spokój"],
  "telc-3339066_1920.jpg": ["telcz", "panorama", "rynek", "kościół", "dachy", "unesco", "architektura", "miasto", "widok"],
  "telc-3362870_1920.jpg": ["telcz", "panorama", "jezioro", "odbicie", "zamek", "miasto", "architektura", "unesco", "spokój"],
  "tower-2687802_1920.jpg": ["wieża", "kamienna", "średniowiecze", "architektura", "historia", "zabytek", "fortyfikacje", "miasto"],
  "tower-3512377_1920.jpg": ["zamek", "cesky sternberk", "wieża", "mur", "architektura", "historia", "forteca", "lato", "chmury"],
  "tower-5475850_1920.jpg": ["cesky krumlov", "panorama", "miasto", "unesco", "dachy", "kościół", "architektura", "historia", "lato"],
  "town-hall-3357010_1920.jpg": ["ratusz", "kościół", "kutna hora", "barok", "architektura", "wieże", "zegar", "historia", "zabytek"],
  "tramway-64006_1280.jpg": ["kolejka linowa", "transport", "miasto", "usti nad labem", "architektura", "technologia", "kościół"],
  "travel-6972025_1920.jpg": ["stacja kolejowa", "tory", "pociąg", "podróż", "peron", "kolej", "transport", "wieś"],
  "trees-6947388_1920.jpg": ["zima", "rzeka", "śnieg", "las", "natura", "krajobraz", "woda", "spokój", "mróz"],
  "tri-3595233_1920.jpg": ["pałac", "troja", "praga", "barok", "architektura", "ogród", "historia", "zabytek", "rzeźba"],
  "tri-3595235_1920.jpg": ["pałac", "troja", "praga", "barok", "fontanna", "ogród", "architektura", "historia", "sztuka"],
  "valdstejnska-e-g-3588079_1920.jpg": ["praga", "ogrody wallensteina", "pałac", "staw", "architektura", "park", "historia", "barok", "zieleń"],
  "valdstejnska-e-g-3588096_1920.jpg": ["praga", "ogrody wallensteina", "pałac", "architektura", "park", "historia", "barok", "fasada", "ogród"],
  "valdstejnska-e-g-3588109_1920.jpg": ["praga", "ogrody wallensteina", "pałac", "architektura", "park", "historia", "barok", "ogród", "spokój"],
  "valdstejnsky-palace-3588101_1920.jpg": ["praga", "pałac wallensteina", "freski", "sztuka", "barok", "wnętrze", "historia", "architektura", "sufit"],
  "village-church-3427592_1920.jpg": ["kościół", "wieś", "architektura", "wzgórze", "drzewa", "religia", "spokój", "lato", "kamień"],
  "vineyard-3359511_1920.jpg": ["kaplica", "winnica", "praga", "troja", "architektura", "wino", "krajobraz", "wiosna", "natura"],
  "vranov-nad-dyji-4322445_1920.jpg": ["zamek", "vranov nad dyją", "skała", "architektura", "lato", "niebo", "historia", "krajobraz", "monument"],
  "water-4687092_1920.jpg": ["rzeka", "las", "natura", "czeska szwajcaria", "wąwóz", "skały", "woda", "spokój", "zieleń"],
  "way-5080085_1920.jpg": ["ścieżka", "park", "aleja", "natura", "krajobraz", "wiosna", "spacer", "zieleń", "spokój"],
  "znojmo-3380665_1920.jpg": ["znojmo", "panorama", "miasto", "architektura", "historia", "krajobraz", "morawy", "widok", "dachy"],
  "znojmo-3403684_1920.jpg": ["znojmo", "rotunda", "romański", "architektura", "historia", "zabytek", "kamień", "kościół", "morawy"],
};