const itemTags = {
  /**
   * =============================================
   * 🇵🇱 POLSKA - TAGI
   * =============================================
   * Strategia:
   * - Używamy małych liter.
   * - Dodajemy słowa kluczowe w j. polskim i angielskim.
   * - Unikamy ogólnego tagu "polska", bo jest on domyślny dla całej galerii.
   * - Skupiamy się na lokalizacji, tematyce i charakterystycznych cechach zdjęcia.
   */

  "architecture-3151102_1920.jpg": ["wrocław", "wroclaw", "uliczka", "alley", "stare miasto", "old town", "bruk", "cobblestone", "sepia", "historia"],
  "autumn-4601377_1920.jpg": ["odra", "oder river", "jesień", "autumn", "kormorany", "cormorants", "rzeka", "river", "natura", "nature", "ptaki", "birds"],
  "autumn-6988012_1920.jpg": ["jesień", "autumn", "rzeka", "river", "pomost", "pier", "las", "forest", "natura", "nature", "kolory", "colors"],
  "azienkowska-route-224316_1920.jpg": ["warszawa", "warsaw", "trasa łazienkowska", "noc", "night", "długi czas naświetlania", "long exposure", "księżyc", "moon"],
  "black-forest-3869476_1920.jpg": ["sudety", "sudetes", "góry", "mountains", "krajobraz", "landscape", "las", "forest", "droga", "road", "natura", "nature"],
  "bobolice-4587868_1920.jpg": ["zamek bobolice", "bobolice castle", "zamek", "castle", "jura", "polish jura", "szlak orlich gniazd", "skały", "rocks"],
  "bydgoszcz-458312_1920.jpg": ["bydgoszcz", "przechodzący przez rzekę", "man crossing the river", "rzeźba", "sculpture", "rzeka brda", "brda river", "miasto", "city"],
  "car-414439_1920.jpg": ["fiat 126p", "maluch", "samochód", "car", "prl", "klasyk", "classic car", "motoryzacja", "automotive"],
  "castle-416847_1920.jpg": ["zamek w gniewie", "gniew castle", "zamek", "castle", "krzyżacy", "teutonic knights", "gotyk", "gothic", "cegła", "brick"],
  "cityscape-9346479_1920.jpg": ["warszawa", "warsaw", "rondo daszyńskiego", "noc", "night", "wieżowce", "skyscrapers", "miasto", "city", "nowoczesność", "modern"],
  "falcon-2795228_1920.jpg": ["sokolica", "pieniny", "góry", "mountains", "sosna", "pine tree", "drzewo", "tree", "symbol", "krajobraz", "landscape"],
  "Gdansk-Stary-Port_Polska_1044857_1920.jpg": ["gdańsk", "gdansk", "motława", "długie pobrzeże", "żuraw", "the crane", "port", "harbor", "stare miasto", "old town"],
  "Gdansk-Ulica-Kamienice_Polska_7856554_1920.jpg": ["gdańsk", "gdansk", "długi targ", "long market", "kamienice", "tenement houses", "dziewczynka", "girl", "stare miasto", "old town"],
  "Gdansk_Polska_7227096_1920.jpg": ["gdańsk", "gdansk", "ulica mariacka", "mariacka street", "stare miasto", "old town", "architektura", "architecture", "bruk", "cobblestone"],
  "Gliwice-Autostrada-Noc_Polska_3248323_1920.jpg": ["gliwice", "autostrada", "motorway", "a1", "a4", "noc", "night", "długi czas naświetlania", "long exposure", "zima", "winter"],
  "Gliwice-Choinka_Christmas-Tree_Polska_3024106_1920.jpg": ["gliwice", "choinka", "christmas tree", "święta", "christmas", "zima", "winter", "ozdoby", "decorations", "geometryczna", "geometric", "światła", "lights"],
  "Gliwice-Park-Jesien_Polska_4565816_1920.jpg": ["gliwice", "park chopina", "park", "jesień", "autumn", "liście", "leaves", "natura", "nature", "relaks", "relax"],
  "Gliwice-Park-Jesien_Polska_4565817_1920.jpg": ["gliwice", "park chopina", "willa", "villa", "jesień", "autumn", "architektura", "architecture", "park"],
  "Gliwice-Park-Jesien_Polska_4565819_1920.jpg": ["gliwice", "palmiarnia", "palm house", "park", "architektura", "architecture", "nowoczesność", "modern", "mgła", "fog"],
  "Gliwice-Park-Natura_Polska_4565821_1920.jpg": ["gliwice", "park", "ławka", "bench", "jesień", "autumn", "liście", "leaves", "melancholia", "melancholy"],
  "Gliwice-Radiostacja_Radio-Station_Polska_742266_1920.jpg": ["gliwice", "radiostacja", "radio tower", "wieża", "tower", "drewno", "wood", "historia", "history", "sepia"],
  "Gliwice-Radiostacja_Radiotower_Polska_5046712_1920.jpg": ["gliwice", "radiostacja", "radio tower", "noc", "night", "błękitna godzina", "blue hour", "wieża", "tower", "historia"],
  "Gliwice-Ratusz_Polska_4634722_1920.jpg": ["gliwice", "rynek", "market square", "ratusz", "town hall", "architektura", "architecture", "miasto", "city"],
  "Gliwice-Rynek-Lato_Polska_4022057_1920.jpg": ["gliwice", "rynek", "market square", "lato", "summer", "miasto", "city", "ratusz", "town hall", "ludzie", "people"],
  "Gliwice-Rynek-Ratusz_Polska_4022055_1920.jpg": ["gliwice", "rynek", "market square", "ratusz", "town hall", "zima", "winter", "śnieg", "snow", "ptaki", "birds"],
  "Gliwice-Rynek-Ratusz_Polska_4634722_1920.jpg": ["gliwice", "rynek", "market square", "ratusz", "town hall", "architektura", "architecture", "miasto", "city", "panorama"],
  "Gliwice-Rzeka_River_Polska_6311462_1920.jpg": ["gliwice", "kanał gliwicki", "gliwice canal", "rzeka", "river", "port", "harbor", "łódź", "boat", "industrialny"],
  "Gliwice-Stare-Miasto_Polska_298230_1920.jpg": ["gliwice", "dworzec kolejowy", "railway station", "zegar", "clock", "architektura", "architecture", "historia", "history", "detal"],
  "Gliwice-Zamek-Zima_Polska_4022052_1920.jpg": ["gliwice", "zamek piastowski", "piast castle", "zamek", "castle", "zima", "winter", "śnieg", "snow", "historia"],
  "Janowiec-Ruiny-Zamku_Castle_Polska_822742_1920.jpg": ["janowiec", "zamek", "castle", "ruiny", "ruins", "wisła", "vistula river", "historia", "history"],
  "jugow-2651002_1920.jpg": ["góry sowie", "owl mountains", "sudety", "sudetes", "jugów", "zima", "winter", "śnieg", "snow", "krajobraz", "landscape"],
  "Katowice-Spodek-Noc_Saucer-Night_Polska_932032_1920.jpg": ["katowice", "spodek", "arena", "noc", "night", "architektura", "architecture", "modernizm", "modernism", "ufo"],
  "Katowice-Spodek_Saucer_Polska_3626971_1920.jpg": ["katowice", "spodek", "arena", "noc", "night", "kładka", "footbridge", "architektura", "architecture"],
  "Katowice-Stacja-Kolejowa_Railway-Station_Polska_377001_1920.jpg": ["katowice", "dworzec kolejowy", "railway station", "neon", "znak", "sign", "architektura", "architecture", "nowoczesność", "modern"],
  "Katowice-Symbol_Polska_2050866_1920.jpg": ["katowice", "rynek", "market square", "napis", "sign", "symbol", "miasto", "city", "zima", "winter"],
  "Kolobrzeg-Ratusz_The-Town-Hall_Polska_3522136_1920.jpg": ["kołobrzeg", "ratusz", "town hall", "neogotyk", "neo-gothic", "architektura", "architecture", "cegła", "brick"],
  "Kolobrzeg_Polska_7562038_1920.jpg": ["kołobrzeg", "port", "harbor", "morze bałtyckie", "baltic sea", "łódki", "boats", "kutry", "fishing boats"],
  "krakow-4854806_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "sukiennice", "cloth hall", "wieża ratuszowa", "town hall tower"],
  "krakow-4854815_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "wieża ratuszowa", "town hall tower", "gotyk", "gothic"],
  "krakow-5213786_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "wieża ratuszowa", "town hall tower", "poranek", "morning"],
  "Krakow-Noc_Polska_poland-82017_1920.jpg": ["kraków", "krakow", "wawel", "zamek", "castle", "noc", "night", "wisła", "vistula river", "odbicie", "reflection"],
  "Krakow-Rynek_Polska_4982314_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "kościół mariacki", "st mary's basilica", "pomnik adama mickiewicza"],
  "Krakow-Sukiennice_Polska_2745231_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "sukiennice", "cloth hall", "dorożka", "horse carriage"],
  "Krakow-Wawel_Polska_wawel-3683040_1920.jpg": ["kraków", "krakow", "wawel", "katedra", "cathedral", "dziedziniec", "courtyard", "architektura", "architecture"],
  "Krakow-Wisla-Noc_Polska_82017_1920.jpg": ["kraków", "krakow", "wawel", "zamek", "castle", "zmierzch", "dusk", "wisła", "vistula river", "odbicie", "reflection"],
  "Krakow_Polska_4982318_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "poranek", "morning", "kościół św wojciecha", "st adalbert's church"],
  "lot-2472183_1920.jpg": ["samolot", "airplane", "lot", "lot polish airlines", "lotnictwo", "aviation", "transport", "embraer"],
  "lublin-3684544_1920.jpg": ["lublin", "fontanna", "fountain", "noc", "night", "światła", "lights", "kolorowy", "colorful", "sylwetka", "silhouette"],
  "Malbork-Zamek_Polska_1104042_1920.jpg": ["malbork", "zamek w malborku", "malbork castle", "zamek", "castle", "krzyżacy", "teutonic knights", "gotyk", "gothic", "rzeka nogat"],
  "martin-procop-1795104_1920.jpg": ["rajd polski", "rally poland", "rajd", "rally", "samochód", "car", "sport", "ford fiesta", "wrc"],
  "masuria-787895_1920.jpg": ["mazury", "masuria", "krajobraz", "landscape", "pola", "fields", "lato", "summer", "natura", "nature"],
  "measles-4601378_1920.jpg": ["ujście warty", "warta mouth national park", "park narodowy", "kormorany", "cormorants", "ptaki", "birds", "natura", "nature"],
  "monument-92826_1920.jpg": ["katowice", "pomnik powstańców śląskich", "silesian insurgents' monument", "pomnik", "monument", "rzeźba", "sculpture", "historia"],
  "monument-92827_1920.jpg": ["katowice", "pomnik powstańców śląskich", "silesian insurgents' monument", "pomnik", "monument", "rzeźba", "sculpture", "detal"],
  "Morskie-Oko_Mountains_Polska_4652861_1920.jpg": ["morskie oko", "tatry", "tatra mountains", "góry", "mountains", "jezioro", "lake", "krajobraz", "landscape", "jesień", "autumn"],
  "Morze-Baltyckie_Baltic-Sea_Polska_7434540_1920.jpg": ["gdynia", "orłowo", "molo", "pier", "morze bałtyckie", "baltic sea", "wschód słońca", "sunrise", "morze", "sea"],
  "Moszna-Mosch-Zamek_Polska.jpg": ["zamek w mosznej", "moszna castle", "zamek", "castle", "pałac", "palace", "architektura", "architecture", "bajkowy", "fairytale"],
  "Moszna-Mosch-Zamek_Polska_mosch-930840_1920.jpg": ["zamek w mosznej", "moszna castle", "zamek", "castle", "oranżeria", "orangery", "architektura", "architecture"],
  "Moszna-Mosch-Zamek_Polska_sabine-930821_960_720.jpg": ["zamek w mosznej", "moszna castle", "zamek", "castle", "pałac", "palace", "odbicie", "reflection", "woda", "water"],
  "mountains-1003778_1920.jpg": ["tatry", "tatra mountains", "góry", "mountains", "zachód słońca", "sunset", "krajobraz", "landscape", "natura", "nature"],
  "mountains-2741921_1920.jpg": ["powroźnik", "cerkiew", "orthodox church", "drewniana architektura", "wooden architecture", "unesco", "beskid sądecki"],
  "mountains-4695270_1920.jpg": ["bieszczady", "góry", "mountains", "połonina wetlińska", "połoniny", "krajobraz", "landscape", "natura", "nature"],
  "muszyna-2741929_1920.jpg": ["muszyna", "maszyna rolnicza", "agricultural machinery", "stary", "old", "rdza", "rust", "wieś", "countryside"],
  "pieniny-989015_1920.jpg": ["pieniny", "góry", "mountains", "wysoki wierch", "szlak", "trail", "krajobraz", "landscape", "panorama"],
  "pieniny-989016_1920.jpg": ["pieniny", "góry", "mountains", "wysoki wierch", "krajobraz", "landscape", "panorama", "jesień", "autumn"],
  "Polana-Kalatowki_Polska_7958161_1920.jpg": ["tatry", "tatra mountains", "kalatówki", "giewont", "góry", "mountains", "wiosna", "spring", "krajobraz", "landscape"],
  "poland-5041875_1920.jpg": ["sokolica", "pieniny", "góry", "mountains", "sosna", "pine tree", "drzewo", "tree", "symbol", "natura"],
  "poland-7898687_1920.jpg": ["warszawa", "warsaw", "biurowce", "office buildings", "architektura", "architecture", "nowoczesność", "modern", "miasto", "city"],
  "Polska-Jura-Zamek_4717062_1920.jpg": ["zamek olsztyn", "olsztyn castle", "jura", "polish jura", "zamek", "castle", "ruiny", "ruins", "szlak orlich gniazd"],
  "Polska-Wilamowice_Polska_5249675_1920.jpg": ["rzepak", "rapeseed", "pole", "field", "wiosna", "spring", "żółty", "yellow", "krajobraz", "landscape", "wieś", "countryside"],
  "poznan-5400771_1920.jpg": ["poznań", "poznan", "jeżyce", "podwórko", "courtyard", "cegła", "brick", "miasto", "city", "klimat", "atmosphere"],
  "Poznan-Rynek_Polska_983563_1920.jpg": ["poznań", "poznan", "stary rynek", "old market square", "kamieniczki budników", "merchants' houses", "architektura", "architecture"],
  "Pszczyna-Lew_Polska_castle-210873_1280.jpg": ["pszczyna", "pleß", "zamek", "castle", "lew", "lion", "rzeźba", "sculpture", "sztuka", "art"],
  "Pszczyna-Rynek_Polska_poland-4717423_1920.jpg": ["pszczyna", "pleß", "rynek", "market square", "kościół", "church", "architektura", "architecture", "miasto", "town"],
  "Pszczyna-Zamek-Lew_Polska_castle-210873_1920.jpg": ["pszczyna", "pleß", "zamek", "castle", "pałac", "palace", "lew", "lion", "rzeźba", "sculpture"],
  "river-96886_1920.jpg": ["san", "rzeka", "river", "sanok", "odbicie", "reflection", "krajobraz", "landscape", "spokój", "calm"],
  "robert-kubica-1795004_1920.jpg": ["robert kubica", "rajd polski", "rally poland", "rajd", "rally", "samochód", "car", "sport", "lotos"],
  "robert-kubica-1795020_1920.jpg": ["robert kubica", "rajd polski", "rally poland", "rajd", "rally", "samochód", "car", "sport", "kurz", "dust"],
  "rock-2579729_1920.jpg": ["maczuga herkulesa", "club of hercules", "ojcowski park narodowy", "jura", "polish jura", "skała", "rock", "natura", "nature"],
  "rocks-999964_1920.jpg": ["ojcowski park narodowy", "jura", "polish jura", "skały", "rocks", "jesień", "autumn", "krajobraz", "landscape"],
  "slowinski-national-park-862262_1920.jpg": ["słowiński park narodowy", "wydmy", "dunes", "piasek", "sand", "zachód słońca", "sunset", "natura", "nature"],
  "Sopot-Monciak_1557406_1920.jpg": ["sopot", "latarnia morska", "lighthouse", "monciak", "architektura", "architecture", "lato", "summer"],
  "Sopot_Polska_6692518_1920.jpg": ["sopot", "grand hotel", "plaża", "beach", "morze bałtyckie", "baltic sea", "molo", "pier", "panorama"],
  "Standarcie-Kawiarnia-Krakow_Polska_street-cafe-4472312_1920.jpg": ["kraków", "krakow", "glonojad", "kawiarnia", "cafe", "restauracja", "restaurant", "ulica", "street"],
  "Swinoujscie_Morze-Baltyckie_Baltic-Sea_Polska_2687131_1920.jpg": ["świnoujście", "swinoujscie", "plaża", "beach", "morze bałtyckie", "baltic sea", "wydmy", "dunes", "wybrzeże", "coast"],
  "szymbark-493405_1920.jpg": ["zamek w szymbarku", "szymbark castle", "zamek", "castle", "ruiny", "ruins", "gotyk", "gothic", "brama", "gate"],
  "szymbark-493406_1920.jpg": ["zamek w szymbarku", "szymbark castle", "zamek", "castle", "ruiny", "ruins", "wieża", "tower", "gotyk", "gothic"],
  "szymbark-493407_1920.jpg": ["zamek w szymbarku", "szymbark castle", "zamek", "castle", "ruiny", "ruins", "gotyk", "gothic", "cegła", "brick"],
  "tanew-3546132_1920.jpg": ["tanew", "rzeka", "river", "szumy", "cascades", "roztocze", "zima", "winter", "lód", "ice", "natura"],
  "tanew-4572905_1920.jpg": ["tanew", "rzeka", "river", "szumy", "cascades", "roztocze", "wodospad", "waterfall", "las", "forest"],
  "tatry-4964656_1920.jpg": ["tatry", "tatra mountains", "góry", "mountains", "czerwone wierchy", "krajobraz", "landscape", "panorama", "szlak", "trail"],
  "tatry-4964670_1920.jpg": ["tatry", "tatra mountains", "góry", "mountains", "babia góra", "panorama", "krajobraz", "landscape", "widok", "view"],
  "tatry-989037_1920.jpg": ["tatry", "tatra mountains", "świnica", "góry", "mountains", "chmury", "clouds", "dramatyczny", "dramatic", "krajobraz", "landscape"],
  "the-ruins-of-the-2714984_1920.jpg": ["siewierz", "zamek", "castle", "ruiny", "ruins", "historia", "history", "architektura", "architecture"],
  "the-ruins-of-the-759068_1920.jpg": ["zamek mirów", "mirów castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd"],
  "tree-4214464_1920.jpg": ["bazie", "catkins", "wierzba", "willow", "wiosna", "spring", "natura", "nature", "zbliżenie", "macro"],
  "Twierdza-Modlin-Narew_Fortress_Polska_7933060_1920.jpg": ["twierdza modlin", "modlin fortress", "forteca", "fortress", "most", "bridge", "rzeka narew", "narew river", "historia"],
  "Twierdza-modlin_modlin-fortress_Narew_Polska_7933060_1920.jpg": ["twierdza modlin", "modlin fortress", "forteca", "fortress", "most", "bridge", "rzeka narew", "narew river", "panorama"],
  "Uznam-Morze-Baltyckie_Zachod-Slonca_Sunset_Polska_7147706_1920.jpg": ["zalew szczeciński", "szczecin lagoon", "zachód słońca", "sunset", "woda", "water", "krajobraz", "landscape", "wolin"],
  "Uznam-Wolin_Usedom_Polska_3621894_1920.jpg": ["świnoujście", "swinoujscie", "latarnia morska", "lighthouse", "port", "harbor", "morze bałtyckie", "baltic sea"],
  "warsaw-2104002_1920.jpg": ["warszawa", "warsaw", "centrum", "city center", "noc", "night", "skyline", "wieżowce", "skyscrapers", "pałac kultury"],
  "warsaw-242997_1920.jpg": ["warszawa", "warsaw", "stare miasto", "old town", "barbakan", "mury obronne", "defensive walls", "noc", "night"],
  "warsaw-242998_1920.jpg": ["warszawa", "warsaw", "stare miasto", "old town", "rynek", "market square", "noc", "night", "kawiarnie", "cafes"],
  "warsaw-243001_1920.jpg": ["warszawa", "warsaw", "krakowskie przedmieście", "noc", "night", "ulica", "street", "światła", "lights"],
  "warsaw-243004_1920.jpg": ["warszawa", "warsaw", "praga", "most poniatowskiego", "noc", "night", "miasto", "city", "długi czas naświetlania", "long exposure"],
  "warsaw-243005_1920.jpg": ["warszawa", "warsaw", "aleje ujazdowskie", "noc", "night", "park", "ławka", "bench", "spokój", "calm"],
  "warsaw-2842681_1920.jpg": ["warszawa", "warsaw", "syrenka", "mermaid", "pomnik", "monument", "stare miasto", "old town", "rynek", "market square"],
  "warsaw-5114457_1920.jpg": ["warszawa", "warsaw", "architektura", "architecture", "kontrast", "contrast", "stare i nowe", "old and new", "miasto", "city"],
  "warsaw-5114463_1920.jpg": ["warszawa", "warsaw", "architektura", "architecture", "detal", "detail", "rzeźba", "sculpture", "kontrast", "contrast"],
  "warsaw-5114470_1920.jpg": ["warszawa", "warsaw", "kamienica", "tenement house", "architektura", "architecture", "detal", "detail", "balkon", "balcony"],
  "warsaw-5123216_1920.jpg": ["warszawa", "warsaw", "park skaryszewski", "park", "rzeźba", "sculpture", "alina", "wiosna", "spring", "kwiaty", "blossoms"],
  "warsaw-5181686_1920.jpg": ["warszawa", "warsaw", "architektura", "architecture", "odbicie", "reflection", "szkło", "glass", "biurowiec", "office building"],
  "warsaw-5181689_1920.jpg": ["warszawa", "warsaw", "budowa", "construction", "dźwig", "crane", "odbicie", "reflection", "architektura", "architecture"],
  "warsaw-5243801_1920.jpg": ["warszawa", "warsaw", "biurowce", "office buildings", "park", "zieleń", "green", "miasto", "city", "nowoczesność", "modern"],
  "warsaw-774238_1920.jpg": ["warszawa", "warsaw", "rondo dmowskiego", "centrum", "city center", "historia", "history", "panorama", "widok z góry", "aerial view"],
  "Warszawa-Pomnik_Polska_2825709_1920.jpg": ["warszawa", "warsaw", "pomnik adama mickiewicza", "monument", "krakowskie przedmieście", "rzeźba", "sculpture"],
  "Warszawa-Stare-Miasto_Polska_910497_1920.jpg": ["warszawa", "warsaw", "plac zamkowy", "castle square", "stare miasto", "old town", "miasto", "city", "ludzie", "people"],
  "Warszawa-Stare-Miasto_Polska_934971_1920.jpg": ["warszawa", "warsaw", "stare miasto", "old town", "rynek", "market square", "kamienice", "tenement houses", "kolorowy"],
  "wisla-2656332_1920.jpg": ["wisła", "beskid śląski", "góry", "mountains", "zima", "winter", "śnieg", "snow", "droga", "road", "krajobraz"],
  "wroclaw-265323_1920.jpg": ["wrocław", "wroclaw", "odra", "oder river", "architektura", "architecture", "kamienica", "tenement house", "zachód słońca", "sunset"],
  "Wroclaw-Rzeka_Polska_2776456_1920.jpg": ["wrocław", "wroclaw", "odra", "oder river", "przystań", "marina", "łódki", "boats", "lato", "summer", "relaks", "relax"],
  "yazzed-al-rajhi-1795044_1920.jpg": ["rajd polski", "rally poland", "rajd", "rally", "samochód", "car", "sport", "ford fiesta", "wrc"],
  "old-street-lamp-335710_1920.jpg": ["gliwice", "kościół wszystkich świętych", "all saints church", "latarnia", "lantern", "wieża", "tower", "gotyk", "gothic", "cegła", "brick", "architektura", "architecture", "detal", "detail"],
  "Gliwice-LO-Ziemowita_Polska_20241017_1920.jpg": ["gliwice", "liceum", "high school", "szkoła", "school", "architektura", "architecture", "cegła", "brick", "budynek", "building", "ziemowita", "historia", "history"],
  "castle-2568548_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "wieża", "tower", "krajobraz", "landscape"],
  "castle-2662673_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "zmierzch", "dusk", "niebo", "sky"],
  "castle-3383242_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "panorama", "zachód słońca", "sunset"],
  "castle-4557894_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "panorama", "lato", "summer", "słoneczny dzień"],
  "castle-4557896_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "dramatyczne", "dramatic", "niebo", "sky"],
  "fencing-1048162_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "okno", "window", "architektura", "architecture"],
  "fencing-1201467_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "mury", "walls", "wzgórze", "hill"],
  "fencing-1258546_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "jesień", "autumn", "liście", "leaves"],
  "fencing-915118_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "mury", "walls", "perspektywa", "perspective"],
  "the-ruins-of-the-2581510_1920.jpg": ["ogrodzieniec", "zamek ogrodzieniec", "ogrodzieniec castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd", "detal", "detail", "sklepienie", "vault", "architektura"],
  "architecture-3067796_1920.jpg": ["wielkopolska", "greater poland", "szkoła", "school", "architektura", "architecture", "cegła", "brick", "zabytek", "historic building"],
  "architecture-3101759_1920.jpg": ["poznań", "poznan", "jeżyce", "kamienica", "tenement house", "secesja", "art nouveau", "architektura", "architecture", "miasto", "city"],
  "architecture-3151082_1920.jpg": ["poznań", "poznan", "kamienica", "tenement house", "modernizm", "modernism", "architektura", "architecture", "budynek", "building"],
  "architecture-3151102_1920.jpg": ["wrocław", "wroclaw", "uliczka", "alley", "stare miasto", "old town", "bruk", "cobblestone", "sepia", "historia"],
  "architecture-3301930_1920.jpg": ["poznań", "poznan", "ostrów tumski", "katedra", "cathedral", "kościół", "church", "gotyk", "gothic", "architektura", "architecture"],
  "architecture-6550356_1920.jpg": ["poznań", "poznan", "stary rynek", "old market square", "ratusz", "town hall", "wieża", "tower", "okno", "window", "architektura", "architecture"],
  "autumn-landscape-2908879_1920.jpg": ["jesień", "autumn", "las", "forest", "ścieżka", "path", "drzewa", "trees", "natura", "nature", "kolory", "colors"],
  "block-4068976_1920.jpg": ["poznań", "poznan", "ostrów tumski", "brama poznania", "porta posnania", "ichot", "nowoczesność", "modern", "architektura", "architecture", "muzeum", "museum"],
  "buildings-657525_1920.jpg": ["poznań", "poznan", "sołacz", "kościół", "church", "architektura", "architecture", "kontrast", "contrast", "cegła", "brick"],
  "bus-station-447101_1920.jpg": ["poznań", "poznan", "dworzec pks", "bus station", "nowoczesność", "modern", "architektura", "architecture", "noc", "night", "światła", "lights"],
  "castle-4999697_1920.jpg": ["poznań", "poznan", "zamek cesarski", "imperial castle", "zamek", "castle", "architektura", "architecture", "neoromanizm", "neo-romanesque"],
  "city-3426704_1920.jpg": ["poznań", "poznan", "jeżyce", "kamienice", "tenement houses", "ulica", "street", "miasto", "city"],
  "city-4999696_1920.jpg": ["poznań", "poznan", "stary rynek", "old market square", "ratusz", "town hall", "bruk", "cobblestone", "miasto", "city"],
  "city-5132735_1920.jpg": ["poznań", "poznan", "stary browar", "old brewery", "centrum handlowe", "shopping mall", "wnętrze", "interior", "architektura", "architecture", "cegła", "brick"],
  "croissant-5209608_1920.jpg": ["rogalin", "pałac w rogalinie", "rogalin palace", "pałac", "palace", "architektura", "architecture", "park", "garden", "wielkopolska", "greater poland"],
  "drone-4539817_1920.jpg": ["poznań", "poznan", "autostrada", "motorway", "a2", "węzeł drogowy", "interchange", "z lotu ptaka", "aerial view", "droga", "road", "las", "forest"],
  "fountain-822945_1920.jpg": ["poznań", "poznan", "plac wolności", "fontanna", "fountain", "noc", "night", "woda", "water", "światła", "lights"],
  "houses-7071276_1920.jpg": ["poznań", "poznan", "stare miasto", "old town", "uliczka", "alley", "noc", "night", "bruk", "cobblestone", "latarnie", "lanterns"],
  "imperial-castle-513161_1920.jpg": ["poznań", "poznan", "zamek cesarski", "imperial castle", "zamek", "castle", "noc", "night", "architektura", "architecture", "neoromanizm"],
  "murals-657519_1920.jpg": ["poznań", "poznan", "mural", "street art", "sztuka miejska", "urban art", "graffiti", "kamienica", "tenement house"],
  "nature-3339460_1920.jpg": ["poznań", "poznan", "park", "park cytadela", "aleja", "alley", "drzewa", "trees", "wiosna", "spring", "natura", "nature"],
  "old-tram-3054142_1920.jpg": ["poznań", "poznan", "tramwaj", "tram", "zabytkowy", "historic", "komunikacja miejska", "public transport", "miasto", "city", "ludzie", "people"],
  "painter-2129415_1920.jpg": ["poznań", "poznan", "ostrów tumski", "katedra", "cathedral", "warta", "rzeka", "river", "malarz", "painter", "sztuka", "art"],
  "park-4549275_1920.jpg": ["rogalin", "pałac w rogalinie", "rogalin palace", "pałac", "palace", "jesień", "autumn", "park", "garden", "architektura", "architecture"],
  "poland-7025079_1920.jpg": ["szlak", "trail", "znak", "sign", "zima", "winter", "śnieg", "snow", "las", "forest", "turystyka", "hiking"],
  "poznan-1541467_1920.jpg": ["poznań", "poznan", "stary rynek", "old market square", "ratusz", "town hall", "renesans", "renaissance", "architektura", "architecture", "zabytek", "monument"],
  "poznan-1670738_1920.jpg": ["poznań", "poznan", "stary rynek", "old market square", "ratusz", "town hall", "restauracje", "restaurants", "wieczór", "evening", "chmury", "clouds"],
  "poznan-2903477_1920.jpg": ["poznań", "poznan", "warta", "rzeka", "river", "ostrów tumski", "katedra", "cathedral", "panorama", "miasto", "city"],
  "poznan-2906170_1920.jpg": ["poznań", "poznan", "stary rynek", "old market square", "kamieniczki budników", "merchants' houses", "kolorowy", "colorful", "architektura", "architecture", "dach", "roof"],
  "poznan-3597202_1920.jpg": ["poznań", "poznan", "ratusz", "town hall", "stary rynek", "old market square", "wieża", "tower", "renesans", "renaissance", "architektura", "architecture"],
  "poznan-4073662_1920.jpg": ["poznań", "poznan", "warta", "rzeka", "river", "architektura", "architecture", "nowe budownictwo", "new development"],
  "poznan-5008490_1920.jpg": ["poznań", "poznan", "fara poznańska", "kolegiata", "kościół", "church", "barok", "baroque", "architektura", "architecture"],
  "poznan-555966_1920.jpg": ["poznań", "poznan", "stary rynek", "old market square", "kamieniczki budników", "merchants' houses", "kolorowy", "colorful", "fasada", "facade", "architektura", "architecture"],
  "poznan-69368_1280.jpg": ["poznań", "poznan", "stary rynek", "old market square", "ratusz", "town hall", "fontanna", "fountain", "rzeźba", "sculpture"],
  "river-3102429_1920.jpg": ["rzeka", "river", "strumień", "stream", "las", "forest", "zima", "winter", "śnieg", "snow", "natura", "nature"],
  "saint-nicholas-day-3859826_1920.jpg": ["poznań", "poznan", "stary rynek", "old market square", "ratusz", "town hall", "kamieniczki budników", "merchants' houses", "kolorowy", "colorful", "poranek", "morning"],
  "stairs-3065064_1920.jpg": ["poznań", "poznan", "collegium altum", "uniwersytet ekonomiczny", "schody", "stairs", "spirala", "spiral", "architektura", "architecture", "wnętrze", "interior"],
  "stairs-3096912_1920.jpg": ["schody", "stairs", "park", "las", "forest", "zima", "winter", "śnieg", "snow", "droga", "path"],
  "the-cathedral-3799811_1920.jpg": ["poznań", "poznan", "ostrów tumski", "katedra", "cathedral", "kościół", "church", "gotyk", "gothic", "zmierzch", "dusk", "most jordana"],
  "the-palace-5209571_1920.jpg": ["rogalin", "pałac w rogalinie", "rogalin palace", "pałac", "palace", "brama", "gate", "droga", "road", "cegła", "brick"],
  "the-palace-5209594_1920.jpg": ["rogalin", "pałac w rogalinie", "rogalin palace", "pałac", "palace", "park", "garden", "trawa", "grass", "lato", "summer"],
  "train-station-447102_1920.jpg": ["poznań", "poznan", "dworzec główny", "main railway station", "kolej", "railway", "nowoczesność", "modern", "architektura", "architecture", "noc", "night"],
  "tram-7924891_1920.jpg": ["poznań", "poznan", "tramwaj", "tram", "mpk poznań", "nowoczesny", "modern", "transport publiczny", "public transport", "miasto", "city"],
  "uniform-727072_1920.jpg": ["poznań", "poznan", "muzeum", "museum", "mundur", "uniform", "historia", "history", "wojsko", "military", "powstanie wielkopolskie"],
  "wall-2924502_1920.jpg": ["poznań", "poznan", "ostrów tumski", "mur", "wall", "cegła", "brick", "gotyk", "gothic", "drzwi", "door", "architektura", "architecture"],
  "winter-3067791_1920.jpg": ["zima", "winter", "szron", "frost", "koszykówka", "basketball", "sport", "detal", "detail", "zimno", "cold"],
  "woman-727073_1920.jpg": ["rekonstrukcja historyczna", "historical reenactment", "strój ludowy", "folk costume", "rękodzieło", "handicraft", "historia", "history", "kobieta", "woman"],
  "advertisement-914068_1920.jpg": ["toruń", "torun", "festiwal światła", "light festival", "bella skyway", "noc", "night", "sztuka", "art", "ludzie", "people"],
  "advertisement-914074_1920.jpg": ["toruń", "torun", "festiwal światła", "light festival", "bella skyway", "noc", "night", "sztuka", "art", "ulica", "street"],
  "advertisement-914079_1920.jpg": ["toruń", "torun", "festiwal światła", "light festival", "bella skyway", "noc", "night", "ludzie", "people", "tłum", "crowd"],
  "advertisement-914083_1920.jpg": ["toruń", "torun", "festiwal światła", "light festival", "bella skyway", "noc", "night", "sztuka", "art", "instalacja", "installation"],
  "architecture-3373921_1920.jpg": ["toruń", "torun", "dwór artusa", "artus court", "architektura", "architecture", "neorenesans", "neo-renaissance", "cegła", "brick", "detal"],
  "artus-court-cultural-center-6564940_1920.jpg": ["toruń", "torun", "dwór artusa", "artus court", "architektura", "architecture", "neorenesans", "cegła", "brick", "detal"],
  "astronomer-2306436_1920.jpg": ["toruń", "torun", "mikołaj kopernik", "nicolaus copernicus", "rzeźba", "sculpture", "sfera armilarna", "armillary sphere", "detal", "detail"],
  "bell-4713231_1920.jpg": ["toruń", "torun", "dzwon", "bell", "tuba dei", "katedra", "cathedral", "historia", "history", "zabytek", "monument"],
  "bridge-3013133_1920.jpg": ["toruń", "torun", "most", "bridge", "wisła", "vistula river", "noc", "night", "odbicie", "reflection", "światła", "lights"],
  "bridge-7769945_1920.jpg": ["toruń", "torun", "most", "bridge", "mgła", "fog", "wisła", "vistula river", "konstrukcja", "structure", "nastrojowe"],
  "church-4829657_1920.jpg": ["toruń", "torun", "kościół", "church", "organy", "pipe organ", "barok", "baroque", "wnętrze", "interior", "sztuka", "art"],
  "church-of-the-holy-spirit-3619165_1920.jpg": ["toruń", "torun", "kościół", "church", "barok", "baroque", "architektura", "architecture", "rynek staromiejski", "old town market square"],
  "city-1148222_1920.jpg": ["toruń", "torun", "architektura", "architecture", "neorenesans", "neo-renaissance", "zabytek", "monument", "budynek", "building"],
  "city-239368_1920.jpg": ["toruń", "torun", "ratusz", "town hall", "gotyk", "gothic", "architektura", "architecture", "rynek staromiejski", "old town market square"],
  "city-4852130_1920.jpg": ["toruń", "torun", "panorama", "wisła", "vistula river", "noc", "night", "katedra", "cathedral", "stare miasto", "old town"],
  "city-4852132_1920.jpg": ["toruń", "torun", "panorama", "wisła", "vistula river", "noc", "night", "katedra", "cathedral", "stare miasto", "old town"],
  "city-6564615_1920.jpg": ["toruń", "torun", "panorama", "stare miasto", "old town", "wisła", "vistula river", "noc", "night", "odbicie", "reflection", "unesco"],
  "city-791279_1920.jpg": ["toruń", "torun", "stare miasto", "old town", "uliczka", "alley", "cegła", "brick", "bluszcz", "ivy", "bruk", "cobblestone"],
  "dill-885783_1920.jpg": ["toruń", "torun", "pomnik", "monument", "mikołaj kopernik", "nicolaus copernicus", "rynek staromiejski", "old town market square", "vintage"],
  "frog-3572497_1920.jpg": ["toruń", "torun", "pomnik flisaka", "raftsman monument", "fontanna", "fountain", "żaba", "frog", "detal", "detail", "legenda", "legend"],
  "gothic-4829682_1920.jpg": ["toruń", "torun", "mury obronne", "city walls", "gotyk", "gothic", "wisła", "vistula river", "starówka", "old town"],
  "monument-195702_1920.jpg": ["toruń", "torun", "kościół", "church", "gotyk", "gothic", "architektura", "architecture", "stare miasto", "old town"],
  "monument-239361_1920.jpg": ["toruń", "torun", "uniwersytet", "university", "umk", "collegium maius", "neogotyk", "neo-gothic", "architektura", "architecture", "cegła", "brick"],
  "nicholas-4829624_1920.jpg": ["toruń", "torun", "pomnik", "monument", "mikołaj kopernik", "nicolaus copernicus", "rzeźba", "sculpture", "jesień", "autumn"],
  "nicholas-4843379_1920.jpg": ["toruń", "torun", "pomnik", "monument", "mikołaj kopernik", "nicolaus copernicus", "rzeźba", "sculpture", "niebo", "sky"],
  "nicholas-4860757_1920.jpg": ["toruń", "torun", "pomnik", "monument", "mikołaj kopernik", "nicolaus copernicus", "rzeźba", "sculpture", "noc", "night", "ratusz"],
  "poland-2773148_1920.jpg": ["toruń", "torun", "spichlerz", "granary", "architektura", "architecture", "gotyk", "gothic", "cegła", "brick", "wisła"],
  "river-4670180_1920.jpg": ["toruń", "torun", "most", "bridge", "wisła", "vistula river", "krajobraz", "landscape", "niebo", "sky"],
  "statue-239366_1920.jpg": ["toruń", "torun", "pomnik", "monument", "pomnik flisaka", "raftsman monument", "rzeźba", "sculpture", "legenda", "legend"],
  "statue-239369_1920.jpg": ["toruń", "torun", "pomnik", "monument", "mikołaj kopernik", "nicolaus copernicus", "rzeźba", "sculpture", "rynek staromiejski", "old town market square"],
  "street-6750106_1920.jpg": ["toruń", "torun", "ulica szeroka", "stare miasto", "old town", "bruk", "cobblestone", "kamienice", "tenement houses", "poranek", "morning"],
  "the-ruins-of-the-1604296_1920.jpg": ["toruń", "torun", "zamek krzyżacki", "teutonic castle", "ruiny", "ruins", "zamek", "castle", "gotyk", "gothic", "cegła", "brick"],
  "the-town-hall-4173338_1920.jpg": ["toruń", "torun", "ratusz", "town hall", "wieża", "tower", "gotyk", "gothic", "architektura", "architecture", "cegła", "brick"],
  "the-town-hall-4173353_1920.jpg": ["toruń", "torun", "ratusz", "town hall", "wieża", "tower", "zegar", "clock", "gotyk", "gothic", "architektura", "architecture"],
  "the-town-hall-4173362_1920.jpg": ["toruń", "torun", "ratusz", "town hall", "rynek staromiejski", "old town market square", "pomnik", "monument", "mikołaj kopernik", "nicolaus copernicus"],
  "torun-2465067_1920.jpg": ["toruń", "torun", "ratusz", "town hall", "wieża", "tower", "gotyk", "gothic", "architektura", "architecture", "zegar", "clock"],
  "torun-3013132_1920.jpg": ["toruń", "torun", "panorama", "wisła", "vistula river", "noc", "night", "odbicie", "reflection", "stare miasto", "old town"],
  "torun-3352310_1920.jpg": ["toruń", "torun", "panorama", "wisła", "vistula river", "stare miasto", "old town", "lato", "summer", "unesco"],
  "torun-3501554_1920.jpg": ["wiosna", "spring", "kwiaty", "flowers", "cebulica", "scilla", "natura", "nature", "niebieski", "blue", "zbliżenie", "macro"],
  "torun-3711031_1920.jpg": ["toruń", "torun", "panorama", "stare miasto", "old town", "wisła", "vistula river", "bulwar filadelfijski", "lato", "summer"],
  "torun-3711032_1920.jpg": ["toruń", "torun", "mury obronne", "city walls", "gotyk", "gothic", "architektura", "architecture", "cegła", "brick", "zabytek"],
  "torun-3817096_1920.jpg": ["toruń", "torun", "panorama", "stare miasto", "old town", "wisła", "vistula river", "most", "bridge", "widok z góry", "aerial view"],
  "torun-419205_1920.jpg": ["toruń", "torun", "panorama", "widok z góry", "aerial view", "stare miasto", "old town", "wisła", "vistula river", "most"],
  "torun-419206_1920.jpg": ["toruń", "torun", "rynek staromiejski", "old town market square", "dwór artusa", "artus court", "panorama", "widok z góry", "aerial view"],
  "torun-419208_1920.jpg": ["toruń", "torun", "panorama", "dachy", "roofs", "stare miasto", "old town", "widok z góry", "aerial view", "unesco"],
  "torun-419210_1920.jpg": ["toruń", "torun", "panorama", "stare miasto", "old town", "wisła", "vistula river", "katedra", "cathedral", "unesco"],
  "torun-456763_1920.jpg": ["toruń", "torun", "brama mostowa", "bridge gate", "brama", "gate", "gotyk", "gothic", "architektura", "architecture", "cegła", "brick"],
  "torun-4769058_1920.jpg": ["toruń", "torun", "stare miasto", "old town", "ulica szeroka", "noc", "night", "święta", "christmas", "dekoracje", "decorations", "światła", "lights"],
  "torun-4772388_1920.jpg": ["toruń", "torun", "pomnik", "monument", "mikołaj kopernik", "nicolaus copernicus", "ratusz", "town hall", "rzeźba", "sculpture"],
  "torun-4829614_1920.jpg": ["toruń", "torun", "panorama", "stare miasto", "old town", "kościół", "church", "widok z góry", "aerial view"],
  "torun-4843129_1920.jpg": ["toruń", "torun", "ratusz", "town hall", "wieża", "tower", "zegar", "clock", "flaga", "flag"],
  "torun-4857967_1920.jpg": ["toruń", "torun", "stare miasto", "old town", "ratusz", "town hall", "noc", "night", "ulica", "street", "bruk", "cobblestone"],
  "torun-4863419_1920.jpg": ["toruń", "torun", "ratusz", "town hall", "wieża", "tower", "noc", "night", "oświetlenie", "illumination", "gotyk"],
  "torun-4863425_1920.jpg": ["toruń", "torun", "ratusz", "town hall", "wieża", "tower", "noc", "night", "detal", "detail", "zegar", "clock"],
  "torun-6049204_1920.jpg": ["toruń", "torun", "kamienica pod gwiazdą", "house under the star", "kamienica", "tenement house", "barok", "baroque", "architektura", "architecture", "czarno-białe"],
  "torun-6049206_1920.jpg": ["toruń", "torun", "brama klasztorna", "city gate", "mury obronne", "city walls", "gotyk", "gothic", "architektura", "architecture", "czarno-białe"],
  "torun-745627_1920.jpg": ["toruń", "torun", "dom kopernika", "copernicus house", "gotyk", "gothic", "architektura", "architecture", "cegła", "brick", "stare miasto", "old town"],
  "torun-916648_1920.jpg": ["toruń", "torun", "festiwal światła", "light festival", "bella skyway", "noc", "night", "sztuka", "art", "lampiony"],
};
