const itemTags = {
  /**
   * =============================================
   * 🇵🇱 POLSKA - TAGI
   * =============================================
   * Strategia:
   * - Używamy małych liter.
   * - Dodajemy słowa kluczowe w j. polskim i angielskim.
   * - Unikamy ogólnego tagu "polska", bo jest on domyślny dla całej galerii.
   * - Skupiamy się na lokalizacji, tematyce i charakterystycznych cechach zdjęcia.
   */

  "architecture-3151102_1920.jpg": ["wrocław", "wroclaw", "uliczka", "alley", "stare miasto", "old town", "bruk", "cobblestone", "sepia", "historia"],
  "autumn-4601377_1920.jpg": ["odra", "oder river", "jesień", "autumn", "kormorany", "cormorants", "rzeka", "river", "natura", "nature", "ptaki", "birds"],
  "autumn-6988012_1920.jpg": ["jesień", "autumn", "rzeka", "river", "pomost", "pier", "las", "forest", "natura", "nature", "kolory", "colors"],
  "azienkowska-route-224316_1920.jpg": ["warszawa", "warsaw", "trasa łazienkowska", "noc", "night", "długi czas naświetlania", "long exposure", "księżyc", "moon"],
  "black-forest-3869476_1920.jpg": ["sudety", "sudetes", "góry", "mountains", "krajobraz", "landscape", "las", "forest", "droga", "road", "natura", "nature"],
  "bobolice-4587868_1920.jpg": ["zamek bobolice", "bobolice castle", "zamek", "castle", "jura", "polish jura", "szlak orlich gniazd", "skały", "rocks"],
  "bydgoszcz-458312_1920.jpg": ["bydgoszcz", "przechodzący przez rzekę", "man crossing the river", "rzeźba", "sculpture", "rzeka brda", "brda river", "miasto", "city"],
  "car-414439_1920.jpg": ["fiat 126p", "maluch", "samochód", "car", "prl", "klasyk", "classic car", "motoryzacja", "automotive"],
  "castle-416847_1920.jpg": ["zamek w gniewie", "gniew castle", "zamek", "castle", "krzyżacy", "teutonic knights", "gotyk", "gothic", "cegła", "brick"],
  "cityscape-9346479_1920.jpg": ["warszawa", "warsaw", "rondo daszyńskiego", "noc", "night", "wieżowce", "skyscrapers", "miasto", "city", "nowoczesność", "modern"],
  "falcon-2795228_1920.jpg": ["sokolica", "pieniny", "góry", "mountains", "sosna", "pine tree", "drzewo", "tree", "symbol", "krajobraz", "landscape"],
  "Gdansk-Stary-Port_Polska_1044857_1920.jpg": ["gdańsk", "gdansk", "motława", "długie pobrzeże", "żuraw", "the crane", "port", "harbor", "stare miasto", "old town"],
  "Gdansk-Ulica-Kamienice_Polska_7856554_1920.jpg": ["gdańsk", "gdansk", "długi targ", "long market", "kamienice", "tenement houses", "dziewczynka", "girl", "stare miasto", "old town"],
  "Gdansk_Polska_7227096_1920.jpg": ["gdańsk", "gdansk", "ulica mariacka", "mariacka street", "stare miasto", "old town", "architektura", "architecture", "bruk", "cobblestone"],
  "Gliwice-Architektura_Polska_2461658_1920.jpg": ["gliwice", "architektura prl", "socrealizm", "modernizm", "miasto", "city", "bloki", "apartment blocks", "ulica", "street"],
  "Gliwice-Autostrada-Noc_Polska_3248323_1920.jpg": ["gliwice", "autostrada", "motorway", "a1", "a4", "noc", "night", "długi czas naświetlania", "long exposure", "zima", "winter"],
  "Gliwice-Choinka_Christmas-Tree_Polska_3024106_1920.jpg": ["gliwice", "rynek", "market square", "choinka", "christmas tree", "święta", "christmas", "zima", "winter"],
  "Gliwice-Park-Jesien_Polska_4565816_1920.jpg": ["gliwice", "park chopina", "park", "jesień", "autumn", "liście", "leaves", "natura", "nature", "relaks", "relax"],
  "Gliwice-Park-Jesien_Polska_4565817_1920.jpg": ["gliwice", "park chopina", "willa", "villa", "jesień", "autumn", "architektura", "architecture", "park"],
  "Gliwice-Park-Jesien_Polska_4565819_1920.jpg": ["gliwice", "palmiarnia", "palm house", "park", "architektura", "architecture", "nowoczesność", "modern", "mgła", "fog"],
  "Gliwice-Park-Natura_Polska_4565821_1920.jpg": ["gliwice", "park", "ławka", "bench", "jesień", "autumn", "liście", "leaves", "melancholia", "melancholy"],
  "Gliwice-Radiostacja_Radio-Station_Polska_742266_1920.jpg": ["gliwice", "radiostacja", "radio tower", "wieża", "tower", "drewno", "wood", "historia", "history", "sepia"],
  "Gliwice-Radiostacja_Radiotower_Polska_5046712_1920.jpg": ["gliwice", "radiostacja", "radio tower", "noc", "night", "błękitna godzina", "blue hour", "wieża", "tower", "historia"],
  "Gliwice-Ratusz_Polska_4634722_1920.jpg": ["gliwice", "rynek", "market square", "ratusz", "town hall", "architektura", "architecture", "miasto", "city"],
  "Gliwice-Rynek-Lato_Polska_4022057_1920.jpg": ["gliwice", "rynek", "market square", "lato", "summer", "miasto", "city", "ratusz", "town hall", "ludzie", "people"],
  "Gliwice-Rynek-Ratusz_Polska_4022055_1920.jpg": ["gliwice", "rynek", "market square", "ratusz", "town hall", "zima", "winter", "śnieg", "snow", "ptaki", "birds"],
  "Gliwice-Rynek-Ratusz_Polska_4634722_1920.jpg": ["gliwice", "rynek", "market square", "ratusz", "town hall", "architektura", "architecture", "miasto", "city", "panorama"],
  "Gliwice-Rzeka_River_Polska_6311462_1920.jpg": ["gliwice", "kanał gliwicki", "gliwice canal", "rzeka", "river", "port", "harbor", "łódź", "boat", "industrialny"],
  "Gliwice-Srodmiescie_Polska_2461654_1920.jpg": ["gliwice", "miasto", "city", "ulica", "street", "architektura", "architecture", "kontrast", "contrast", "prl"],
  "Gliwice-Stare-Miasto_Polska_298230_1920.jpg": ["gliwice", "dworzec kolejowy", "railway station", "zegar", "clock", "architektura", "architecture", "historia", "history", "detal"],
  "Gliwice-Zamek-Zima_Polska_4022052_1920.jpg": ["gliwice", "zamek piastowski", "piast castle", "zamek", "castle", "zima", "winter", "śnieg", "snow", "historia"],
  "Janowiec-Ruiny-Zamku_Castle_Polska_822742_1920.jpg": ["janowiec", "zamek", "castle", "ruiny", "ruins", "wisła", "vistula river", "historia", "history"],
  "jugow-2651002_1920.jpg": ["góry sowie", "owl mountains", "sudety", "sudetes", "jugów", "zima", "winter", "śnieg", "snow", "krajobraz", "landscape"],
  "Katowice-Spodek-Noc_Saucer-Night_Polska_932032_1920.jpg": ["katowice", "spodek", "arena", "noc", "night", "architektura", "architecture", "modernizm", "modernism", "ufo"],
  "Katowice-Spodek_Saucer_Polska_3626971_1920.jpg": ["katowice", "spodek", "arena", "noc", "night", "kładka", "footbridge", "architektura", "architecture"],
  "Katowice-Stacja-Kolejowa_Railway-Station_Polska_377001_1920.jpg": ["katowice", "dworzec kolejowy", "railway station", "neon", "znak", "sign", "architektura", "architecture", "nowoczesność", "modern"],
  "Katowice-Symbol_Polska_2050866_1920.jpg": ["katowice", "rynek", "market square", "napis", "sign", "symbol", "miasto", "city", "zima", "winter"],
  "Kolobrzeg-Ratusz_The-Town-Hall_Polska_3522136_1920.jpg": ["kołobrzeg", "ratusz", "town hall", "neogotyk", "neo-gothic", "architektura", "architecture", "cegła", "brick"],
  "Kolobrzeg_Polska_7562038_1920.jpg": ["kołobrzeg", "port", "harbor", "morze bałtyckie", "baltic sea", "łódki", "boats", "kutry", "fishing boats"],
  "krakow-4854806_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "sukiennice", "cloth hall", "wieża ratuszowa", "town hall tower"],
  "krakow-4854815_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "wieża ratuszowa", "town hall tower", "gotyk", "gothic"],
  "krakow-5213786_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "wieża ratuszowa", "town hall tower", "poranek", "morning"],
  "Krakow-Noc_Polska_poland-82017_1920.jpg": ["kraków", "krakow", "wawel", "zamek", "castle", "noc", "night", "wisła", "vistula river", "odbicie", "reflection"],
  "Krakow-Rynek_Polska_4982314_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "kościół mariacki", "st mary's basilica", "pomnik adama mickiewicza"],
  "Krakow-Sukiennice_Polska_2745231_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "sukiennice", "cloth hall", "dorożka", "horse carriage"],
  "Krakow-Wawel_Polska_wawel-3683040_1920.jpg": ["kraków", "krakow", "wawel", "katedra", "cathedral", "dziedziniec", "courtyard", "architektura", "architecture"],
  "Krakow-Wisla-Noc_Polska_82017_1920.jpg": ["kraków", "krakow", "wawel", "zamek", "castle", "zmierzch", "dusk", "wisła", "vistula river", "odbicie", "reflection"],
  "Krakow_Polska_4982318_1920.jpg": ["kraków", "krakow", "rynek główny", "main market square", "poranek", "morning", "kościół św wojciecha", "st adalbert's church"],
  "lot-2472183_1920.jpg": ["samolot", "airplane", "lot", "lot polish airlines", "lotnictwo", "aviation", "transport", "embraer"],
  "lublin-3684544_1920.jpg": ["lublin", "fontanna", "fountain", "noc", "night", "światła", "lights", "kolorowy", "colorful", "sylwetka", "silhouette"],
  "Malbork-Zamek_Polska_1104042_1920.jpg": ["malbork", "zamek w malborku", "malbork castle", "zamek", "castle", "krzyżacy", "teutonic knights", "gotyk", "gothic", "rzeka nogat"],
  "martin-procop-1795104_1920.jpg": ["rajd polski", "rally poland", "rajd", "rally", "samochód", "car", "sport", "ford fiesta", "wrc"],
  "masuria-787895_1920.jpg": ["mazury", "masuria", "krajobraz", "landscape", "pola", "fields", "lato", "summer", "natura", "nature"],
  "measles-4601378_1920.jpg": ["ujście warty", "warta mouth national park", "park narodowy", "kormorany", "cormorants", "ptaki", "birds", "natura", "nature"],
  "monument-92826_1920.jpg": ["katowice", "pomnik powstańców śląskich", "silesian insurgents' monument", "pomnik", "monument", "rzeźba", "sculpture", "historia"],
  "monument-92827_1920.jpg": ["katowice", "pomnik powstańców śląskich", "silesian insurgents' monument", "pomnik", "monument", "rzeźba", "sculpture", "detal"],
  "Morskie-Oko_Mountains_Polska_4652861_1920.jpg": ["morskie oko", "tatry", "tatra mountains", "góry", "mountains", "jezioro", "lake", "krajobraz", "landscape", "jesień", "autumn"],
  "Morze-Baltyckie_Baltic-Sea_Polska_7434540_1920.jpg": ["gdynia", "orłowo", "molo", "pier", "morze bałtyckie", "baltic sea", "wschód słońca", "sunrise", "morze", "sea"],
  "Moszna-Mosch-Zamek_Polska.jpg": ["zamek w mosznej", "moszna castle", "zamek", "castle", "pałac", "palace", "architektura", "architecture", "bajkowy", "fairytale"],
  "Moszna-Mosch-Zamek_Polska_mosch-930840_1920.jpg": ["zamek w mosznej", "moszna castle", "zamek", "castle", "oranżeria", "orangery", "architektura", "architecture"],
  "Moszna-Mosch-Zamek_Polska_sabine-930821_960_720.jpg": ["zamek w mosznej", "moszna castle", "zamek", "castle", "pałac", "palace", "odbicie", "reflection", "woda", "water"],
  "mountains-1003778_1920.jpg": ["tatry", "tatra mountains", "góry", "mountains", "zachód słońca", "sunset", "krajobraz", "landscape", "natura", "nature"],
  "mountains-2741921_1920.jpg": ["powroźnik", "cerkiew", "orthodox church", "drewniana architektura", "wooden architecture", "unesco", "beskid sądecki"],
  "mountains-4695270_1920.jpg": ["bieszczady", "góry", "mountains", "połonina wetlińska", "połoniny", "krajobraz", "landscape", "natura", "nature"],
  "muszyna-2741929_1920.jpg": ["muszyna", "maszyna rolnicza", "agricultural machinery", "stary", "old", "rdza", "rust", "wieś", "countryside"],
  "pieniny-989015_1920.jpg": ["pieniny", "góry", "mountains", "wysoki wierch", "szlak", "trail", "krajobraz", "landscape", "panorama"],
  "pieniny-989016_1920.jpg": ["pieniny", "góry", "mountains", "wysoki wierch", "krajobraz", "landscape", "panorama", "jesień", "autumn"],
  "Polana-Kalatowki_Polska_7958161_1920.jpg": ["tatry", "tatra mountains", "kalatówki", "giewont", "góry", "mountains", "wiosna", "spring", "krajobraz", "landscape"],
  "poland-5041875_1920.jpg": ["sokolica", "pieniny", "góry", "mountains", "sosna", "pine tree", "drzewo", "tree", "symbol", "natura"],
  "poland-7898687_1920.jpg": ["warszawa", "warsaw", "biurowce", "office buildings", "architektura", "architecture", "nowoczesność", "modern", "miasto", "city"],
  "Polska-Jura-Zamek_4717062_1920.jpg": ["zamek olsztyn", "olsztyn castle", "jura", "polish jura", "zamek", "castle", "ruiny", "ruins", "szlak orlich gniazd"],
  "Polska-Wilamowice_Polska_5249675_1920.jpg": ["rzepak", "rapeseed", "pole", "field", "wiosna", "spring", "żółty", "yellow", "krajobraz", "landscape", "wieś", "countryside"],
  "poznan-5400771_1920.jpg": ["poznań", "poznan", "jeżyce", "podwórko", "courtyard", "cegła", "brick", "miasto", "city", "klimat", "atmosphere"],
  "Poznan-Rynek_Polska_983563_1920.jpg": ["poznań", "poznan", "stary rynek", "old market square", "kamieniczki budników", "merchants' houses", "architektura", "architecture"],
  "Pszczyna-Lew_Polska_castle-210873_1280.jpg": ["pszczyna", "pleß", "zamek", "castle", "lew", "lion", "rzeźba", "sculpture", "sztuka", "art"],
  "Pszczyna-Rynek_Polska_poland-4717423_1920.jpg": ["pszczyna", "pleß", "rynek", "market square", "kościół", "church", "architektura", "architecture", "miasto", "town"],
  "Pszczyna-Zamek-Lew_Polska_castle-210873_1920.jpg": ["pszczyna", "pleß", "zamek", "castle", "pałac", "palace", "lew", "lion", "rzeźba", "sculpture"],
  "river-96886_1920.jpg": ["san", "rzeka", "river", "sanok", "odbicie", "reflection", "krajobraz", "landscape", "spokój", "calm"],
  "robert-kubica-1795004_1920.jpg": ["robert kubica", "rajd polski", "rally poland", "rajd", "rally", "samochód", "car", "sport", "lotos"],
  "robert-kubica-1795020_1920.jpg": ["robert kubica", "rajd polski", "rally poland", "rajd", "rally", "samochód", "car", "sport", "kurz", "dust"],
  "rock-2579729_1920.jpg": ["maczuga herkulesa", "club of hercules", "ojcowski park narodowy", "jura", "polish jura", "skała", "rock", "natura", "nature"],
  "rocks-999964_1920.jpg": ["ojcowski park narodowy", "jura", "polish jura", "skały", "rocks", "jesień", "autumn", "krajobraz", "landscape"],
  "slowinski-national-park-862262_1920.jpg": ["słowiński park narodowy", "wydmy", "dunes", "piasek", "sand", "zachód słońca", "sunset", "natura", "nature"],
  "Sopot-Monciak_1557406_1920.jpg": ["sopot", "latarnia morska", "lighthouse", "monciak", "architektura", "architecture", "lato", "summer"],
  "Sopot_Polska_6692518_1920.jpg": ["sopot", "grand hotel", "plaża", "beach", "morze bałtyckie", "baltic sea", "molo", "pier", "panorama"],
  "Standarcie-Kawiarnia-Krakow_Polska_street-cafe-4472312_1920.jpg": ["kraków", "krakow", "glonojad", "kawiarnia", "cafe", "restauracja", "restaurant", "ulica", "street"],
  "Swinoujscie_Morze-Baltyckie_Baltic-Sea_Polska_2687131_1920.jpg": ["świnoujście", "swinoujscie", "plaża", "beach", "morze bałtyckie", "baltic sea", "wydmy", "dunes", "wybrzeże", "coast"],
  "szymbark-493405_1920.jpg": ["zamek w szymbarku", "szymbark castle", "zamek", "castle", "ruiny", "ruins", "gotyk", "gothic", "brama", "gate"],
  "szymbark-493406_1920.jpg": ["zamek w szymbarku", "szymbark castle", "zamek", "castle", "ruiny", "ruins", "wieża", "tower", "gotyk", "gothic"],
  "szymbark-493407_1920.jpg": ["zamek w szymbarku", "szymbark castle", "zamek", "castle", "ruiny", "ruins", "gotyk", "gothic", "cegła", "brick"],
  "tanew-3546132_1920.jpg": ["tanew", "rzeka", "river", "szumy", "cascades", "roztocze", "zima", "winter", "lód", "ice", "natura"],
  "tanew-4572905_1920.jpg": ["tanew", "rzeka", "river", "szumy", "cascades", "roztocze", "wodospad", "waterfall", "las", "forest"],
  "tatry-4964656_1920.jpg": ["tatry", "tatra mountains", "góry", "mountains", "czerwone wierchy", "krajobraz", "landscape", "panorama", "szlak", "trail"],
  "tatry-4964670_1920.jpg": ["tatry", "tatra mountains", "góry", "mountains", "babia góra", "panorama", "krajobraz", "landscape", "widok", "view"],
  "tatry-989037_1920.jpg": ["tatry", "tatra mountains", "świnica", "góry", "mountains", "chmury", "clouds", "dramatyczny", "dramatic", "krajobraz", "landscape"],
  "the-ruins-of-the-2714984_1920.jpg": ["siewierz", "zamek", "castle", "ruiny", "ruins", "historia", "history", "architektura", "architecture"],
  "the-ruins-of-the-759068_1920.jpg": ["zamek mirów", "mirów castle", "zamek", "castle", "ruiny", "ruins", "jura", "polish jura", "szlak orlich gniazd"],
  "tree-4214464_1920.jpg": ["bazie", "catkins", "wierzba", "willow", "wiosna", "spring", "natura", "nature", "zbliżenie", "macro"],
  "Twierdza-Modlin-Narew_Fortress_Polska_7933060_1920.jpg": ["twierdza modlin", "modlin fortress", "forteca", "fortress", "most", "bridge", "rzeka narew", "narew river", "historia"],
  "Twierdza-modlin_modlin-fortress_Narew_Polska_7933060_1920.jpg": ["twierdza modlin", "modlin fortress", "forteca", "fortress", "most", "bridge", "rzeka narew", "narew river", "panorama"],
  "Uznam-Morze-Baltyckie_Zachod-Slonca_Sunset_Polska_7147706_1920.jpg": ["zalew szczeciński", "szczecin lagoon", "zachód słońca", "sunset", "woda", "water", "krajobraz", "landscape", "wolin"],
  "Uznam-Wolin_Usedom_Polska_3621894_1920.jpg": ["świnoujście", "swinoujscie", "latarnia morska", "lighthouse", "port", "harbor", "morze bałtyckie", "baltic sea"],
  "warsaw-2104002_1920.jpg": ["warszawa", "warsaw", "centrum", "city center", "noc", "night", "skyline", "wieżowce", "skyscrapers", "pałac kultury"],
  "warsaw-242997_1920.jpg": ["warszawa", "warsaw", "stare miasto", "old town", "barbakan", "mury obronne", "defensive walls", "noc", "night"],
  "warsaw-242998_1920.jpg": ["warszawa", "warsaw", "stare miasto", "old town", "rynek", "market square", "noc", "night", "kawiarnie", "cafes"],
  "warsaw-243001_1920.jpg": ["warszawa", "warsaw", "krakowskie przedmieście", "noc", "night", "ulica", "street", "światła", "lights"],
  "warsaw-243004_1920.jpg": ["warszawa", "warsaw", "praga", "most poniatowskiego", "noc", "night", "miasto", "city", "długi czas naświetlania", "long exposure"],
  "warsaw-243005_1920.jpg": ["warszawa", "warsaw", "aleje ujazdowskie", "noc", "night", "park", "ławka", "bench", "spokój", "calm"],
  "warsaw-2842681_1920.jpg": ["warszawa", "warsaw", "syrenka", "mermaid", "pomnik", "monument", "stare miasto", "old town", "rynek", "market square"],
  "warsaw-5114457_1920.jpg": ["warszawa", "warsaw", "architektura", "architecture", "kontrast", "contrast", "stare i nowe", "old and new", "miasto", "city"],
  "warsaw-5114463_1920.jpg": ["warszawa", "warsaw", "architektura", "architecture", "detal", "detail", "rzeźba", "sculpture", "kontrast", "contrast"],
  "warsaw-5114470_1920.jpg": ["warszawa", "warsaw", "kamienica", "tenement house", "architektura", "architecture", "detal", "detail", "balkon", "balcony"],
  "warsaw-5123216_1920.jpg": ["warszawa", "warsaw", "park skaryszewski", "park", "rzeźba", "sculpture", "alina", "wiosna", "spring", "kwiaty", "blossoms"],
  "warsaw-5181686_1920.jpg": ["warszawa", "warsaw", "architektura", "architecture", "odbicie", "reflection", "szkło", "glass", "biurowiec", "office building"],
  "warsaw-5181689_1920.jpg": ["warszawa", "warsaw", "budowa", "construction", "dźwig", "crane", "odbicie", "reflection", "architektura", "architecture"],
  "warsaw-5243801_1920.jpg": ["warszawa", "warsaw", "biurowce", "office buildings", "park", "zieleń", "green", "miasto", "city", "nowoczesność", "modern"],
  "warsaw-774238_1920.jpg": ["warszawa", "warsaw", "rondo dmowskiego", "centrum", "city center", "historia", "history", "panorama", "widok z góry", "aerial view"],
  "Warszawa-Pomnik_Polska_2825709_1920.jpg": ["warszawa", "warsaw", "pomnik adama mickiewicza", "monument", "krakowskie przedmieście", "rzeźba", "sculpture"],
  "Warszawa-Stare-Miasto_Polska_910497_1920.jpg": ["warszawa", "warsaw", "plac zamkowy", "castle square", "stare miasto", "old town", "miasto", "city", "ludzie", "people"],
  "Warszawa-Stare-Miasto_Polska_934971_1920.jpg": ["warszawa", "warsaw", "stare miasto", "old town", "rynek", "market square", "kamienice", "tenement houses", "kolorowy"],
  "wisla-2656332_1920.jpg": ["wisła", "beskid śląski", "góry", "mountains", "zima", "winter", "śnieg", "snow", "droga", "road", "krajobraz"],
  "wroclaw-265323_1920.jpg": ["wrocław", "wroclaw", "odra", "oder river", "architektura", "architecture", "kamienica", "tenement house", "zachód słońca", "sunset"],
  "Wroclaw-Rzeka_Polska_2776456_1920.jpg": ["wrocław", "wroclaw", "odra", "oder river", "przystań", "marina", "łódki", "boats", "lato", "summer", "relaks", "relax"],
  "yazzed-al-rajhi-1795044_1920.jpg": ["rajd polski", "rally poland", "rajd", "rally", "samochód", "car", "sport", "ford fiesta", "wrc"],
};